### ISSUE TITLE
python interface defaults

### ISSUE THREAD

**Issue by rubinsky** [eudaq/eudaq#106]
when connecting with a pybar python producer to the RC on NI FHLAIDA
`python eudaq_ext_trigger.py tcp://192.168.3.3`
Command Thread exiting due to exception:
```
Error looking up address 'FHLAIDA': 
  From /home/telescope/eudaq/main/lib/src/TransportTCP.cc:532
  In void eudaq::TCPClient::OpenConnection()
```

this can be solved by editing /etc/hosts file to have
```
127.0.0.1       localhost
127.0.1.1       atlaslab13
192.168.3.2     FHLDATURA
192.168.3.3     FHLAIDA

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

then FHLAIDA is not unresolved anymore, however this networking is complicated enough to have it defined by IPs.

**Comment by simonspa** [comment]
Network configuration is certainly a non-trivial thing but nothing we can provide as-is from withinn EUDAQ. Closing this ticket.
