### ISSUE TITLE
CMS constant is not defined 

### ISSUE THREAD

**Issue by RPeschke** [eudaq/eudaq#124]
CMS constant is not defined 

/eudaq/trunk/nreader/detdescription/EUTelSetupDescription.cc:55:42: error: ‘kCMSPixel’ was not declared in this scope
   else if ( typeS == "CMSPixel") typeE = kCMSPixel;
                                          ^
make[2]: *** [CMakeFiles/DetectorDescriptons.dir/nreader/detdescription/EUTelSetupDescription.cc.o] Error 1
make[1]: *** [CMakeFiles/DetectorDescriptons.dir/all] Error 2

**Comment by simonspa** [comment]
Ah sh***. I have to merge my cmspixel TGeo description into EUTelescope master.

Thanks for the reminder.

Am 8. April 2015 19:55:16 MESZ, schrieb RPeschke <notifications@github.com>:
