### ISSUE TITLE
FYI Errors while compiling...

### ISSUE THREAD

**Issue by thomaseichhorn** [eudaq/eudaq#139]
Occured on CMS workgroup server:

/main/lib/src/Utils.cc: In function ‘void eudaq::mSleep(unsigned int)’:
/main/lib/src/Utils.cc:94:5: error: ‘sleep_for’ is not a member of ‘std::this_thread’

**Comment by simonspa** [comment]
This seems to be a specific problem of GCC 4.6 which can be cured by adding the addition CXX flag
```
-D_GLIBCXX_USE_NANOSLEEP
```
to the make call (or in CMake to the cxx_flags()).
