### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by superbello** [eudaq/eudaq#160]
Just a note to say that standard compiled root from source (version 5.34.32) would not compile with -lPhysics available afterwards. Running the root configure script with option --all brought it in and runs fine.

**Comment by simonspa** [comment]
Hi @superbello,

do you have the exact compilation error which would point us to the ROOT libraries missing in the standard configuration? We should probably document them in the installation manual.

/Simon

**Comment by superbello** [comment]
Hi Simon
It was -lPhysics, missing for me.
Cheers,
Jens

**Comment by simonspa** [comment]
Great, thanks, I misunderstood your first note.
I added the requirement to the installation instruction.
