### ISSUE TITLE
OfflineMonitor Axis 

### ISSUE THREAD

**Issue by superbello** [eudaq/eudaq#161]
Axis pre-scaling for the Correlation versus time plot does 4 iterations of:
axisA->[min/max]_scalefaktorX-axisA->[min/max]_scalefaktorY-offset
where it should be doing
axisA->[min/max]_scalefaktorX-axisB->[min/max]_scalefaktorY-offset
Needs to be fixed to keep monitoring the correlation on samples where the channel number on sample B is larger than sample A

**Comment by arummler** [comment]
Done with PR #307
