### ISSUE TITLE
Use Qt File Choosed Dialog for conf Files

### ISSUE THREAD

**Issue by dreyling** [eudaq/eudaq#168]
If you add a conf-file in the conf-folder, it only appears in the drop-down menu after a restart of euRun. Is there a possibility to update this list by not terminating euRun?

**Comment by simonspa** [comment]
It would be better to replace this dropdown menu with a simple
(Qt-provided) file selection dialog. This would also remove the
restriction to the "conf" folder.

**Comment by arummler** [comment]
I started to work on that (works already in principle) and will add also settings persistence through QSettings. It will be probably ready by the end of the week.

**Comment by simonspa** [comment]
Pretty awesome.
We're close to merging all 2.0 work to master, so things are getting there... :)

**Comment by arummler** [comment]
pull request #171

**Comment by simonspa** [comment]
Awesomely fixed by @arummler in #171, merged to master and v1.5-dev.
