### ISSUE TITLE
Issues found when compiling eudaq master branch (EUDAQ v2.0)

### ISSUE THREAD

**Issue by airqui** [eudaq/eudaq#173]
Hi,

Thanks for the new version! I just tried to compile it and I have found few issues that might not be visible for people using EUTELESCOPE libraries.

We compile by doing:
> cmake -DUSE_LCIO=ON -DBUILD_calice=ON ..
> make install
(not EUTELESCOPE libraries!!)

I have found two  issues:

The first is an error in the LCIOC filewriter:
/home/calice/eudaq2-calice-devel/main/lib/src/FileWriterLCIOC.cc:37:12: error: ‘RegisterFileWriter’ does not name a type

Is easily fixable changing these lines
  //  namespace {                   few
  //  static RegisterFileWriter<FileWriterLCIOC> reg("calice");          
  registerFileWriter(FileWriterLCIOC, "calice");
  //}  

The second is a set of issues that are all related to the non-presence of the EUTELESCOPE libraries and headers in our setup. So far I have found that "#if USE_EUTELESCOPE" are missing on several files.

Cheers,
Adrian

**Comment by arummler** [comment]
I also now get a missing "Collection_createIfNotExist" in SCTConverterPlugin.cc
This function seems to have been removed in DataConverterPlugin.h/.cc with commit dfb04b2e03438def4e401f8f91d902a3cd09ef4f

**Comment by arummler** [comment]
Pull request #177

**Comment by arummler** [comment]
@simonspa This issue can be closed as #177 has been merged.

**Comment by simonspa** [comment]
Awesome.
