### ISSUE TITLE
cmake error CMP0002 in master and v1.5 when using option nreader

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#183]
I get a cmake error since yesterday when building the nreader library. I am not sure why now as I am not aware of a change in the cmake version.
-- Determined EUDAQ version v1.5.1+31~gced60a6*

 CMake` Error at CMakeLists.txt:218 (add_custom_target):
   add_custom_target cannot create target "uninstall" because another target
   with the same name already exists.  The existing target is a custom target
   created in source directory
   "/home/rummler/Software/eutelescope/installed_v011703/v01-17-05/Eutelescope/trunk/external/eudaq/trunk/nreader".
   See documentation for policy CMP0002 for more detail

**Comment by simonspa** [comment]
This is probably a result of 357b18ed6c5c19406ad5a7bb2783e2d4b63c3c0f

However, I don't completely get it since before there was no `uninstall` target existing - we didn't define one. But since I want to move to installing eudaq to /usr/local instead of running it from the source folder I thought uninstalling might be a nice option...

**Comment by simonspa** [comment]
Not sure it was triggered by this commit, but the Windows build now fails: https://ci.appveyor.com/project/simonspa/eudaq

**Comment by arummler** [comment]
I think I know what's happening: you are missing the appveyor.yml file in the v1.5-dev branch and thus it is running with empty "standard" settings. Furthermore, I just realized that I left my testing branch name in. There will be two PR in 5 minutes.

**Comment by arummler** [comment]
Shall I cherry pick everything from master into v1.5-dev? I think I do not dare to do a rebase.

**Comment by simonspa** [comment]
Nah, no rebasing, that's evil. Just cherry-pick, that's fine with me.
