### ISSUE TITLE
Build test on Windows using AppveyorCI

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#184]
@simonspa, I played around with appveyor today and managed to get it working including the compilation of the OnlineMon. According to
https://github.com/blog/1935-see-results-from-all-pull-request-status-checks
github supports multiple CIs at the same time. Thus we could just add appveyor for the Windows build and keep TravisCI for Linux and Mac. What do you think? I can add the appveyor.yml to my next PR if you want.
![bildschirmfoto vom 2016-02-09 01 34 52](https://cloud.githubusercontent.com/assets/2855671/12904203/de37ea1c-cecd-11e5-867d-6fef9f5e8bf3.png)

**Comment by simonspa** [comment]
Sure, awesome!

**Comment by arummler** [comment]
Okay, checked in with PR  #185

**Comment by simonspa** [comment]
PR merged, builds on AppVeyor started.
Now having CI for Windows builds.
