### ISSUE TITLE
Python wrapper missing file resulting in cmake error

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#186]
CMake Error at main/python/CMakeLists.txt:5 (ADD_LIBRARY):
   Cannot find source file:

     src/PyIndexReader.cpp

   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
   .hxx .in .txx

**Comment by arummler** [comment]
It seems it was removed (incompletely) with commit  9cdb156532d06de3b78139f640532a68002dd58d but there is no explanation why.

**Comment by arummler** [comment]
If I remove it from the CMakeLists.txt it gets stuck a bit later during compiling
[ 70%] Building CXX object main/python/CMakeFiles/PyAidaFileReader.dir/src/PyAidaFileReader.cpp.o
/home/rummler/Software/eutelescope/installed_v011703/v01-17-05/Eutelescope/trunk/external/eudaq/trunk/main/python/src/PyAidaFileReader.cpp:78:35: fatal error: eudaq/AidaFileReader.hh: No such file or directory
 #include "eudaq/AidaFileReader.hh"
                                   ^
compilation terminated.
[ 71%] Built target TestReader
[ 71%] Built target TestRunControl

[ 74%] Built target euProd
[ 75%] /home/rummler/Software/eutelescope/installed_v011703/v01-17-05/Eutelescope/trunk/external/eudaq/trunk/main/python/src/PyProducer.cpp:6:31: fatal error: eudaq/AidaPacket.hh: No such file or directory
 #include "eudaq/AidaPacket.hh"

**Comment by simonspa** [comment]
mentioning @druxx

**Comment by arummler** [comment]
Seems to work now in v1.7-dev
