### ISSUE TITLE
AHCAL and CALICE in EUDAQ1 branch

### ISSUE THREAD

**Issue by airqui** [eudaq/eudaq#194]
Hi,

I would propose to add last changes that have been implemented in the calice producers in the latest eudaq 1 repository since many of the detectors and testbeams of the calice collaboration will continue using eudaq 1 in the short term and having everything in the same repository will be very helpful for the community...

The latest version of the code that I have is in the branch:
https://github.com/airqui/eudaq/tree/ahcal_contribution

It was pulled to the master branch which I assumed (probably I missunderstood this) that was planned to be separated in two (the stable release of eudaq 1 and the developing version of eudaq 2) when all producers where there, but seems that now the master is the eudaq 2 and there is the only place where the calice producers are (despite of my own fork).

I wait for your answer to make a pull request since it might be more changes in eudaq1 after my previous accepted pull request. Just tell me if you agree and how do you want to proceed.

Cheers,
Adrian

**Comment by simonspa** [comment]
Hi @airqui 

you are right that `master` contains all developments towards EUDAQ2, while the branch `v1.5-dev` serves as base for further maintenance of EUDAQ1.x.

/Simon

**Comment by airqui** [comment]
Hi @simonspa 
So, I will just request a pull of my ahcal_contribution to the v1.5-dev
cheers,
Adrian

**Comment by simonspa** [comment]
merged.
