### ISSUE TITLE
CaliceGenericConverterPlugin

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#197]
This converter plugin produces a warning with MSVC.
`C:\projects\eudaq\main\lib\plugins\CaliceGenericConverterPlugin.cc(71): warning C4018: '<' : signed/unsigned mismatch [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]`

It should be enough to change line 67 from
`int nblock =4; // the first 4 blocks contain information`
to
`unsigned int nblock =4; // the first 4 blocks contain information`
Could the owner of the plugin please check that?

**Comment by simonspa** [comment]
@airqui could you please check this?

**Comment by airqui** [comment]
no problem, il do it.

**Comment by arummler** [comment]
Checked that this is fixed for v1.6-dev.
