### ISSUE TITLE
Warnings: PALPIDEFSConverterPlugin

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#199]
There are a bunch of warnings thrown by MSVC within this converter plugin. Could the maintainer please check them out and correct them?
> C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(235): warning C4244: '=' : conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1093): warning C4244: '+=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1094): warning C4244: '+=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1095): warning C4244: '+=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1096): warning C4244: '+=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1112): warning C4244: '=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1117): warning C4244: '=' : conversion from 'Double_t' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1118): warning C4244: '/=' : conversion from 'double' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]
C:\projects\eudaq\main\lib\plugins\PALPIDEFSConverterPlugin.cc(1119): warning C4244: '/=' : conversion from 'double' to 'float', possible loss of data [C:\projects\eudaq\build\main\lib\EUDAQ.vcxproj]

**Comment by simonspa** [comment]
mentioning @freidt

**Comment by arummler** [comment]
Checked that this is fixed for v1.6-dev.
