### ISSUE TITLE
The feature of automatic loading and configurating different config files in a folder doesn't work anymore?

### ISSUE THREAD

**Issue by airqui** [eudaq/eudaq#214]
Dear all,
I have tried the feature of automatic loading and config of *.conf files and it does not work anymore.
We have tried in November and it worked well:

Run control version 1.5.1+17~gc38d470 (note that this version was previous of the versions that implemented the load buttton).

I tried few newer versions and it fails:
1.5.1+63~g7118abf*
and the latest
1.5.1+146~gf16339

and fails. I attach you a screen shot of the log window and the status of the run control window when it fails. We don't receive any error message in the terminal. The sequence of actions before the error are:

Load a confif file.
Config click.
Start click.
Automatic Stop.
--> the run control waits a bit and then try to load a new config file (or I expect that, at leas) and then everything in the run control window goes white. 
No errors in the terminal.

To activate the automatic loading, I use the following options in my conf file:

[RunControl]
RunEventLimit = 200
NextConfigFileOnFileLimit = 1

Cheers,
Adrian

![error_loading_conf_files_eudaq](https://cloud.githubusercontent.com/assets/1118831/14910488/1aee2ca0-0dee-11e6-8441-7c0b88de8aaa.png)

**Comment by arummler** [comment]
Hi,
it might have broken when I changed the dialogue for loading the config file. It tried to preserve it but did not test it afterwards. If I remember correctly I also made some commit which touches this that is not yet merged. I am afraid that today I won't have time to look into it or only very late. Is it urgent?
Cheers,
Andre

**Comment by airqui** [comment]
Is not that urgent. We have testbeam next week but we will need one day and a half to setup everything. If it works for that time will be great and we will test eudaq1 and 2 in the beam area, if not we will need to live with eudaq 1 (the version from november work for us).

Thanks a lot!
A.

**Comment by arummler** [comment]
With PR #215  it should work again. Please try it out. I applied it to the current v1.5-dev and also to my development branch arummler/v1.5-dev-integration_prs_april_2016 where I included all pending PRs for v1.5-dev.

What do you mean by eudaq1/2 in this context? Everything that lives on 1.5-dev is still eudaq1, only 2.0-dev is eudaq2 (with the major changes in structure).

**Comment by airqui** [comment]
Hi,
I a bit confused on what the master branch contains, I assumed that was containing the eudaq2 developments, right?
Cheers,
Adrian

**Comment by arummler** [comment]
Hi,
yes this is correct. I did not understand your remark "we will test eudaq1 and 2 in the beam area, if not we will need to live with eudaq 1 (the version from november work for us)." as you were talking about stuff you took from v1.5-dev and implied eudaq2.

**Comment by arummler** [comment]
@airqui Did you have a chance to test it? Did my fix work?

**Comment by airqui** [comment]
Hi, it works! Thanks a lot!

**Comment by arummler** [comment]
Excellent, thanks for the feedback. Closing.
