### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#233]
@Eyiliu After your commits the onlinemonitor no longer compiles on windows. There might be an issue with your changed cmake scripts as the include file <cstdint> cannot be found anymore.

**Comment by Eyiliu** [comment]
@arummler   
Looks like missing cstdint. Try the stdint.h   .
I try to rebuild  it  on AppVeyor twice. Appveyor return false:
Command exited with code -1073741502 
I think it is another issue. Any idea?

**Comment by Eyiliu** [comment]
fixed
