### ISSUE TITLE
src/CaliceGenericConverterPlugin.cc missing

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#249]
@airqui  
In the calice/CMakeLists.txt
there is file
src/CaliceGenericConverterPlugin.cc
requested which does not exist after the reordering.

CMake Error at producers/calice/CMakeLists.txt:10 (ADD_LIBRARY):

  Cannot find source file:

    src/CaliceGenericConverterPlugin.cc

**Comment by airqui** [comment]
Thanks, is fixed now.
