### ISSUE TITLE
NI entry in BORE malformed

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#276]
Type=_RAW:NI, Number=1673.4294967295, Flags=BORE, {BOARDS=6, DET=MIMOSA26, ID=11, ID=12, ID=19, ID=4, ID=2, ID=20, MIMOSA_EN=1, MIMOSA_EN=1, MIMOSA_EN=1, MIMOSA_EN=1, MIMOSA_EN=1, MIMOSA_EN=1, MODE=ZS2}

special characters in front of =

**Comment by simonspa** [comment]
called here:
https://github.com/eudaq/eudaq/blob/v1.7-dev/producers/ni/src/NiProducer.cxx#L170

violator is `eudaq::to_string()` rountein here
https://github.com/eudaq/eudaq/blob/v1.7-dev/main/include/eudaq/Utils.hh#L54
which simply outputs the unsigned char to ostream.

Fix by replacing `unsigned char` with regular `unsigned int` here:
https://github.com/eudaq/eudaq/blob/v1.7-dev/producers/ni/src/NiProducer.cxx#L167
and here:
https://github.com/eudaq/eudaq/blob/v1.7-dev/producers/ni/src/NiProducer.cxx#L169

**Comment by arummler** [comment]
Thanks, did not hunt it down yet. But do we actually still need this utility function? C++11 offers to_string() natively.

**Comment by simonspa** [comment]
we probably don't since we're relying in C++11 anyway...

Go for cleaning up! :)

**Comment by arummler** [comment]
Fixing with 491758982a0fd24fd77d7f57d1330af91f99eb2e as proposed by Simon.
Will check whether to_string() can be dropped.

**Comment by arummler** [comment]
Okay, this does not work as the helper function offers more formatting choices.
