### ISSUE TITLE
Update README.release_notes

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#292]
end at 1.3.1

**Comment by dreyling** [comment]
This probably moved to here???
https://github.com/eudaq/eudaq/releases

**Comment by arummler** [comment]
You are right, it seems a redundant. Either we delete the file (but between 1.0 and 1.2 there seems to some information only in the file) or add a sentence on the top like. "This file with release informations is no longer maintained, please consult the new list under https://github.com/eudaq/eudaq/releases"?

**Comment by arummler** [comment]
Added the line.
