### ISSUE TITLE
Installation EUDAQ Software

### ISSUE THREAD

**Issue by cpuggion** [eudaq/eudaq#334]
Dear,
I'm trying Install a eudaq, because I would try to write the producer for a chip that will be tested with this telescope. But at some point I give me an error that I do not understand. I hope you can help me. Below follow the information that might be useful to understand the problem:
Operating system: Scientific Linux 6.8
CMake Version: 3.8.0-rc2
gcc 4.9.2
devtoolset-3

I am following the following steps:
git clone https://github.com/eudaq/eudaq.git eudaq
eudaq cd /
git tag
git checkout v1.6.0
cd build
cmake ..  //Bellow follow the output:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /opt/rh/devtoolset-3/root/usr/bin/gcc
-- Check for working C compiler: /opt/rh/devtoolset-3/root/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using gcc-specific preprocessor identifiers
-- Main EUDAQ library directory is clean (all changes have been commited).
-- Determined EUDAQ version v1.6.0
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Protobuf (missing:  Protobuf_INCLUDE_DIR) 
-- Looking for Root...
-- Found ROOT: /usr/bin/root (found version 5.34/36)
-- Looking for CMSPixel dependencies: pxarCore...
-- NOT building converter plugin for CMSPixel.
-- Could not find Qt5, searching for Qt4 instead...
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.6.2") 
-- Found Qt 4.6.2, will build GUI executables
-- Looking for Root...
-- Found ROOT: /usr/bin/root (found version 5.34/36)
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- CMAKE_BINARY_DIR: /home/muoni/eudaq/build
-- PROJECT_SOURCE_DIR: /home/muoni/eudaq
-- This is CMake 3.8.0-rc2 (/opt/usr/local/bin/cmake) running on Linux (2.6.32-642.el6.x86_64 "Scientific Linux release 6.8 (Carbon)")
-- 64-bit compiler detected
-- Using GNU (/opt/rh/devtoolset-3/root/usr/bin/c++) version 4.9.2
-- Compiler Flags: -fPIC 
-- With COMPILE_DEFINITIONS = EUDAQ_PLATFORM=PF_LINUX;EUDAQ_FUNC=__PRETTY_FUNCTION__ ;_GLIBCXX_USE_NANOSLEEP
-- Found PythonInterp: /usr/bin/python (found version "2.6.6") 
-- *** Build Type RelWithDebInfo ***
-- *** Compiler Flags:  -fPIC
-- *** Compiler Flags:  -fPIC
-- Configuring done
-- Generating done
-- Build files have been written to: /home/muoni/eudaq/build

make install        //Bellow follow the output:
Scanning dependencies of target EUDAQ
[  0%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/AidaFileReader.cc.o
[  1%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/AidaFileWriter.cc.o
[  2%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/AidaIndexData.cc.o
[  2%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/AidaPacket.cc.o
[  3%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/BufferSerializer.cc.o
[  3%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/CommandReceiver.cc.o
[  4%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Configuration.cc.o
[  5%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/DEPFETEvent.cc.o
[  5%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/DataCollector.cc.o
[  6%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/DataSender.cc.o
[  6%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/DetectorEvent.cc.o
[  7%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/DummyProducer.cc.o
[  8%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/EUDRBEvent.cc.o
[  8%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Event.cc.o
[  9%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/EventSynchronisationBase.cc.o
[  9%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/ExampleHardware.cc.o
[ 10%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Exception.cc.o
[ 11%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileNamer.cc.o
[ 11%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileReader.cc.o
[ 12%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileSerializer.cc.o
[ 12%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriter.cc.o
[ 13%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterDetectorEvents.cc.o
[ 14%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterLCIO.cc.o
[ 14%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterLCIOC.cc.o
[ 15%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterMimoloop.cc.o
[ 15%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterNative.cc.o
[ 16%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterNative2.cc.o
[ 17%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterNull.cc.o
[ 17%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterRoot.cc.o
[ 18%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterRootC.cc.o
[ 18%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterStandard.cc.o
[ 19%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterText.cc.o
[ 20%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterTextCompact.cc.o
[ 20%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/FileWriterTree.cc.o
[ 21%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/IndexReader.cc.o
[ 21%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/LogCollector.cc.o
[ 22%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/LogMessage.cc.o
[ 23%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/LogSender.cc.o
[ 23%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Logger.cc.o
[ 24%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/MetaData.cc.o
[ 24%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Monitor.cc.o
[ 25%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/MultiFileReader.cc.o
[ 26%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Mutex.cc.o
[ 26%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/OptionParser.cc.o
[ 27%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/PluginManager.cc.o
[ 27%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Producer.cc.o
[ 28%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/RawDataEvent.cc.o
[ 29%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/RunControl.cc.o
[ 29%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Serializable.cc.o
[ 30%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/StandardEvent.cc.o
[ 30%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Status.cc.o
[ 31%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/StringEvent.cc.o
[ 32%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TLU2Packet.cc.o
[ 32%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TLUEvent.cc.o
[ 33%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Time.cc.o
[ 33%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportBase.cc.o
[ 34%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportClient.cc.o
[ 35%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportFactory.cc.o
[ 35%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportNULL.cc.o
[ 36%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportServer.cc.o
[ 36%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/TransportTCP.cc.o
[ 37%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/Utils.cc.o
[ 38%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/APIX-CT-ConverterPlugin.cc.o
[ 38%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/AltroUSBConverterPlugin.cc.o
[ 39%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/CLICpixConverterPlugin.cc.o
[ 39%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/CaliceGenericConverterPlugin.cc.o
[ 40%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/CcpdlfADCConverterPlugin.cc.o
[ 41%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/CcpdlfConverterPlugin.cc.o
[ 41%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/DEPFETConverterPlugin.cc.o
[ 42%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/DataConverterPlugin.cc.o
[ 42%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/EUDRBConverterPlugin.cc.o
[ 43%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/ExampleConverterPlugin.cc.o
[ 44%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/ExplorerConverterPlugin.cc.o
[ 44%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/FORTISConverterPlugin.cc.o
[ 45%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/MVDConverterPlugin.cc.o
[ 45%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/MimosaConverterPlugin.cc.o
[ 46%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/Mupix2ConverterPlugin.cc.o
[ 47%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/Mupix3ConverterPlugin.cc.o
[ 47%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/Mupix4ConverterPlugin.cc.o
[ 48%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/NIConverterPlugin.cc.o
[ 48%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/PALPIDEFSConverterPlugin.cc.o
[ 49%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/PALPIDESSConverterPlugin.cc.o
[ 50%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/PyBARConverterPlugin.cc.o
[ 50%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/SCTConverterPlugin.cc.o
[ 51%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/SCTUpgradeConverterPlugin.cc.o
[ 51%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/TAKIConverterPlugin.cc.o
[ 52%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/TLUConverterPlugin.cc.o
[ 53%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/TestConverterPlugin.cc.o
[ 53%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/TimepixConverterPlugin.cc.o
[ 54%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/USBPixI4ConverterPlugin.cc.o
[ 54%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/USBpixConverterPlugin.cc.o
[ 55%] Linking CXX shared library libEUDAQ.so
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lPhysics
collect2: error: ld returned 1 exit status
make[2]: *** [main/lib/libEUDAQ.so] Error 1
make[1]: *** [main/lib/CMakeFiles/EUDAQ.dir/all] Error 2
make: *** [all] Error 2

What am I doing wrong? I forgot to install something?
Thank you in advance for your help
Best Regards
Carlo

**Comment by arummler** [comment]
Hello,
unfortunately I do not have SLC here and lxplus gives me strange errors. Try to use the current development branch v1.7-dev If I remember correctly I changed at some time the linking order as I had such a problem on Ubuntu. gcc is getting stricter with regard to the linking order. This is a good idea anyhow as 1.6.0 still uses the old FSM and there was an API change. I hope to tag 1.7.0 soon.

**Comment by eyiliu** [comment]
It is a link error /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lPhysics.
libPhysics.so is a ROOT library.  However I think this ROOT library is not necessary.

**Comment by arummler** [comment]
That's indeed correct, the physics lib is at least not directly used. But root-config --glibs is  used to compile the list of root-libraries for the linke. If it is not available while root-config claims it is there might be something strange ongoing with the root installation. You can also check the actually used command by using:
make VERBOSE=1

**Comment by cpuggion** [comment]
Dear eyiliu and arummler,
thank you for your answers.
I tried with  branch v1.7-dev but i've the same problem.
If the problem is my root installation i can try to install it again.
bellow you can found the output of make VERBOSE=1
[ 55%] Linking CXX shared library libEUDAQ.so
cd /home/muoni/eudaq/build/main/lib && /opt/usr/local/bin/cmake -E cmake_link_script CMakeFiles/EUDAQ.dir/link.txt --verbose=1
/opt/rh/devtoolset-3/root/usr/bin/c++ -fPIC -fPIC -O2 -g -DNDEBUG  -shared -Wl,-soname,libEUDAQ.so -o libEUDAQ.so CMakeFiles/EUDAQ.dir/src/AidaFileReader.cc.o CMakeFiles/EUDAQ.dir/src/AidaFileWriter.cc.o CMakeFiles/EUDAQ.dir/src/AidaIndexData.cc.o CMakeFiles/EUDAQ.dir/src/AidaPacket.cc.o CMakeFiles/EUDAQ.dir/src/BufferSerializer.cc.o CMakeFiles/EUDAQ.dir/src/CommandReceiver.cc.o CMakeFiles/EUDAQ.dir/src/Configuration.cc.o CMakeFiles/EUDAQ.dir/src/DEPFETEvent.cc.o CMakeFiles/EUDAQ.dir/src/DataCollector.cc.o CMakeFiles/EUDAQ.dir/src/DataSender.cc.o CMakeFiles/EUDAQ.dir/src/DetectorEvent.cc.o CMakeFiles/EUDAQ.dir/src/DummyProducer.cc.o CMakeFiles/EUDAQ.dir/src/EUDRBEvent.cc.o CMakeFiles/EUDAQ.dir/src/Event.cc.o CMakeFiles/EUDAQ.dir/src/EventSynchronisationBase.cc.o CMakeFiles/EUDAQ.dir/src/ExampleHardware.cc.o CMakeFiles/EUDAQ.dir/src/Exception.cc.o CMakeFiles/EUDAQ.dir/src/FileNamer.cc.o CMakeFiles/EUDAQ.dir/src/FileReader.cc.o CMakeFiles/EUDAQ.dir/src/FileSerializer.cc.o CMakeFiles/EUDAQ.dir/src/FileWriter.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterDetectorEvents.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterLCIO.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterLCIOC.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterMimoloop.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterNative.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterNative2.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterNull.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterRoot.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterRootC.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterStandard.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterText.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterTextCompact.cc.o CMakeFiles/EUDAQ.dir/src/FileWriterTree.cc.o CMakeFiles/EUDAQ.dir/src/IndexReader.cc.o CMakeFiles/EUDAQ.dir/src/LogCollector.cc.o CMakeFiles/EUDAQ.dir/src/LogMessage.cc.o CMakeFiles/EUDAQ.dir/src/LogSender.cc.o CMakeFiles/EUDAQ.dir/src/Logger.cc.o CMakeFiles/EUDAQ.dir/src/MetaData.cc.o CMakeFiles/EUDAQ.dir/src/Monitor.cc.o CMakeFiles/EUDAQ.dir/src/MultiFileReader.cc.o CMakeFiles/EUDAQ.dir/src/Mutex.cc.o CMakeFiles/EUDAQ.dir/src/OptionParser.cc.o CMakeFiles/EUDAQ.dir/src/PluginManager.cc.o CMakeFiles/EUDAQ.dir/src/Producer.cc.o CMakeFiles/EUDAQ.dir/src/RawDataEvent.cc.o CMakeFiles/EUDAQ.dir/src/RunControl.cc.o CMakeFiles/EUDAQ.dir/src/Serializable.cc.o CMakeFiles/EUDAQ.dir/src/StandardEvent.cc.o CMakeFiles/EUDAQ.dir/src/Status.cc.o CMakeFiles/EUDAQ.dir/src/StringEvent.cc.o CMakeFiles/EUDAQ.dir/src/TLU2Packet.cc.o CMakeFiles/EUDAQ.dir/src/TLUEvent.cc.o CMakeFiles/EUDAQ.dir/src/Time.cc.o CMakeFiles/EUDAQ.dir/src/TransportBase.cc.o CMakeFiles/EUDAQ.dir/src/TransportClient.cc.o CMakeFiles/EUDAQ.dir/src/TransportFactory.cc.o CMakeFiles/EUDAQ.dir/src/TransportNULL.cc.o CMakeFiles/EUDAQ.dir/src/TransportServer.cc.o CMakeFiles/EUDAQ.dir/src/TransportTCP.cc.o CMakeFiles/EUDAQ.dir/src/Utils.cc.o CMakeFiles/EUDAQ.dir/plugins/APIX-CT-ConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/AltroUSBConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/CLICpixConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/CaliceGenericConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/CcpdlfADCConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/CcpdlfConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/DEPFETConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/DataConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/EUDRBConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/ExampleConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/ExplorerConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/FORTISConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/MVDConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/MimosaConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/Mupix2ConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/Mupix3ConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/Mupix4ConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/NIConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/PALPIDEFSConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/PALPIDESSConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/PyBARConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/SCTConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/SCTUpgradeConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/TAKIConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/TLUConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/TestConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/TimepixConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/USBPixI4ConverterPlugin.cc.o CMakeFiles/EUDAQ.dir/plugins/USBpixConverterPlugin.cc.o -Wl,-rpath,::::::::::::::::::::: -lpthread -L/usr/lib64/root -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -lMinuit 
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lPhysics
collect2: error: ld returned 1 exit status
make[2]: *** [main/lib/libEUDAQ.so] Error 1
make[2]: Leaving directory `/home/muoni/eudaq/build'
make[1]: *** [main/lib/CMakeFiles/EUDAQ.dir/all] Error 2
make[1]: Leaving directory `/home/muoni/eudaq/build'
make: *** [all] Error 2

**Comment by freidt** [comment]
Ciao @cpuggion,

do you use a root version which is installed via yum?
This seems like a common problem, which I observed using the root installed via the package manager.

Have you tried to compile root from the sources?

Cheers,
Felix

**Comment by cpuggion** [comment]
Dear all,
I want inform you that I fixed the problem.
I installed the root-physics rpm from 
http://rpm.pbone.net/index.php3/stat/4/idpl/34461961/dir/redhat_el_6/com/root-physics-5.34.36-1.el6.x86_64.rpm.html
Now I installed eudaq with successful. 
Thanks for your help.
Carlo

**Comment by dreyling** [comment]
I think, you don't need the online monitor for developing. If so, just
switch off building it:
cmake - DBUILD_onlinemon= off ..

See also EUDAQ manual.

Am 08.03.2017 11:36 vorm. schrieb "freidt" <notifications@github.com>:

> Ciao @cpuggion,
>
> do you use a root version which is installed via yum?
> This seems like a common problem, which I observed using the root
> installed via the package manager.
>
> Have you tried to compile root from the sources?
>
> Cheers,
> Felix
>

**Comment by arummler** [comment]
Summary: Reason was a broken root installation (Personally, I compile it always myself because there are no official packages and the one time I checked everything offered by third-party was incredibly outdated and also compiled with strange parameters).  @cpuggion If there are further problems please do not hesitate and open a new issue, I will close this one now.
