### ISSUE TITLE
RPi does no longer compile

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#344]
Changes in wiringlib require adding the crypt and rt libraries to the linker. I am writing cmake modules for that.

**Comment by simonspa** [comment]
Better get rid if wiringPi in the first place. It's not a very nice
library anyway and we only use a small fraction which we might also
implement directly.

**Comment by arummler** [comment]
@simonspa I have seen there are also other libraries like pigpio but as I nether used the raspberry I do not know how good they are.  Thinking about the issue: One could also just (not even rpi specific) have a controller or even producer that just receives a peace of python code during its init or config step and executes it either immediately or by callback. In this case basically it would download a little snippet
import RPi.GPIO as GPIO
import time
time.sleep(4)
GPIO.output(13,True)

Solved with PR #347
