### ISSUE TITLE
config file error in euRun not reported but trigger segmentation fault

### ISSUE THREAD

**Issue by MengqingWu** [eudaq/eudaq#356]
-- **master branch** ---
There will be some pre-filled ini and conf files when opening a euRun executable dialog.
If the configure file does **not exist**, the following error will be popped-up:

INFO: Initializing ...(/home/kpix/afs/eudaq/eudaq/conf/test.ini) 2017-05-10 11:59:41.320
INFO: Initialized 2017-05-10 11:59:41.322
CommandReceiver::ProcessThread() Error: Uncaught exception: SocketClient Error (11): 
  From /home/kpix/afs/eudaq/eudaq/main/lib/core/src/TransportTCP.cc:556
  In virtual void eudaq::TCPClient::ProcessEvents(int)

[1]-  Segmentation fault      (core dumped) ./euRun -a tcp://44000

@eyiliu

**Comment by eyiliu** [comment]
Thank you for the issue report. Fixed
