### ISSUE TITLE
Fail to compile eudaq/v1.7.dev against eutelescope/master with nreader and CMSPixel=ON

### ISSUE THREAD

**Issue by j1990grossmann** [eudaq/eudaq#372]
ILCSOFT/v01-19-02/Eutelescope/master/external/eudaq/./main/include/eudaq/CMSPixelHelper.hh: In member function ‘virtual bool eudaq::CMSPixelHelper::GetLCIOSubEvent(EVENT::LCEvent&, const eudaq::Event&) const’:
ILCSOFT/v01-19-02/Eutelescope/master/external/eudaq/./main/include/eudaq/CMSPixelHelper.hh:203:24: error: ‘class eutelescope::EUTelTrackerDataInterfacerImpl<eutelescope::EUTelGenericSparsePixel>’ has no member named ‘addSparsePixel’
           sparseFrame->addSparsePixel(sparsePixel.get());
                        ^
make[2]: *** [main/lib/CMakeFiles/EUDAQ.dir/plugins/CMSPixelConverterPlugin.cc.o] Error 1

**Comment by j1990grossmann** [comment]
For a fix pleas check the pull request.

**Comment by arummler** [comment]
merged #373
