### ISSUE TITLE
Coverity administrator?

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#376]
Hi,
last year I tried to add eudaq to my coverity account in order to run an analysis/add it to the travis configuration. Eudaq is registered since 2014 with coverity - does anybody know who the admin is? I never got approved.

**Comment by simonspa** [comment]
It might be @hperrey

**Comment by hperrey** [comment]
@simonspa is right -- I just authorized you as admin/owner on coverty.

**Comment by arummler** [comment]
Okay, thanks.
