### ISSUE TITLE
findCACTUS.cmake does not look under /opt  ( it should )

### ISSUE THREAD

**Issue by DavidCussans** [eudaq/eudaq#381]
findCACTUS.cmake does not look under /opt/cacus  . This is the standard location if IPBus/Cactus is installed on SL6/ SL7 / CentOS7  

Suggested fix: Add /opt/cactus in list of directories searched in findCACTUS.cmake

**Comment by eyiliu** [comment]
Thank you for the suggestion. It is fixed
