### ISSUE TITLE
FmctluProducer doesn't stop run cleanly unless triggers are running.

### ISSUE THREAD

**Issue by DavidCussans** [eudaq/eudaq#382]
Problems stopping run cleanly.

If the triggers are not running there are problems. To reproduce:

Run FmctluProducer

Start run , with no triggers running.

Press "Stop" on run control Gui. ( The run won't stop. )

Press "Stop" on run control Gui repeatedly. ( The run still won't stop )

Send a stream of triggers into TLU

... get error message:

INFO: Stopping Run 2017-08-31 13:02:28.935
THROW: OnStopRun can not be called unless in STATE_RUNNING 2017-08-31 13:02:30.094
Caught exception: OnStopRun can not be called unless in STATE_RUNNING
  From /home/osboxes/AIDA/eudaq/main/lib/core/src/Producer.cc:93
  In virtual void eudaq::Producer::OnStopRun()
THROW: OnStopRun can not be called unless in STATE_RUNNING 2017-08-31 13:02:30.179
Caught exception: OnStopRun can not be called unless in STATE_RUNNING
  From /home/osboxes/AIDA/eudaq/main/lib/core/src/Producer.cc:93
  In virtual void eudaq::Producer::OnStopRun()

( etc. etc. - depending on how many times Stop was pressed I presume ).

------

If the triggers *are* running, then most of the time the FmctluProducer won't stop either ....

**Comment by eyiliu** [comment]
Can you explain clearly about "start run, with no triggers running"? 

In pricinple, a producer should start itself sucessfully, and then return a status of "running". Otherwise, if a producer detector any issue of running. A error should be announced.

**Comment by DavidCussans** [comment]
The triggers were generated using a pulse generator connected to a trigger input of TLU.

The current fmcTLU producer doesn't reliably transition from RUNNING to STOPPED states when commanded to by euRun

**Comment by DavidCussans** [comment]
We haven't seen this issue recently. When we saw the issue we were running the TLU producer on a virtual machine. Currently we are running on a "real" machine. Perhaps this is the reason why we don't see the problem.

Don't have the time to reproduce the problem --> Close issue.
