### ISSUE TITLE
Typographical error on p23 of the v2.0.1 manual 

### ISSUE THREAD

**Issue by DavidCussans** [eudaq/eudaq#397]
In section 4.5.2
states

To convert Event from data file, the tool euCliConverter is provided. The command
line pattern is: The command line pattern is:
euCliReader -i {input_file} -o {output_file} -ip

... it should read

To convert Event from data file, the tool euCliConverter is provided. The command
line pattern is: The command line pattern is:
euCliConverter -i {input_file} -o {output_file} -ip

**Comment by arummler** [comment]
done
