### ISSUE TITLE
Wrong display of APIX quad module in OnlineMonitor

### ISSUE THREAD

**Issue by agisen** [eudaq/eudaq#401]
The hitmap of APIX quad modules is displayed wrongly in the OnlineMonitor: Rows are on x-Axis, cols are on y-Axis.

Koji pointed out to me that this can be fixed with changing 
`if(rowmult>1)
plane.SetSizeZS(rowmult*NROW, colmult*NCOL, 0, m_nFrames, StandardPlane::FLAG_DIFFCOORDS | StandardPlane::FLAG_ACCUMULATE);`
to 
`if(rowmult>1)
		plane.SetSizeZS(colmult*NCOL, rowmult*NROW, 0, m_nFrames, StandardPlane::FLAG_DIFFCOORDS | StandardPlane::FLAG_ACCUMULATE);`
in APIXCTConverterPlugin::GetStandardSubEvent() in main/lib/plugins/APIX-CT-ConverterPlugin.cc

In my point of you this makes the whole if statement unnecessary, if `rowmult` is added to the `else` statement.

**Comment by arummler** [comment]
Fixed, duplicates #402
