### ISSUE TITLE
euLog crashes on start

### ISSUE THREAD

**Issue by DavidLP** [eudaq/eudaq#410]
`euRun` is started and `euLog` crashes with:

```bash
user@silab:~/git/eudaq/bin$ ./euLog 
INFO: TCPServer:: Listening on port 53851 2018-02-22 16:49:15.590
THROW: CommandReceiver: Invalid response from RunControl: 'OK EUDAQ CMD RunControl' 2018-02-22 16:49:15.674
terminate called after throwing an instance of 'eudaq::LoggedException'
  what():  CommandReceiver: Invalid response from RunControl: 'OK EUDAQ CMD RunControl'
  From /home/user/git/eudaq/main/lib/core/src/CommandReceiver.cc:344
  In std::string eudaq::CommandReceiver::Connect()
Aborted (core dumped)
```

**Comment by dreyling** [comment]
What EUDAQ version are you using? 
Are you running on the same machine?
Do you have a "sleep" (~2 sec.) between starting `euRun` and `euLog`?

**Comment by DavidLP** [comment]
> What EUDAQ version are you using?

Master,  b7efbd8

> Are you running on the same machine?

Yes

> Do you have a "sleep" (~2 sec.) between starting euRun and euLog?

Yes

**Comment by dreyling** [comment]
Ok, at my OS (Ubuntu 16) it is starting and connecting  properly...?

**Comment by DavidLP** [comment]
I rebuild the project and it is working now. Thank you for your support!
