### ISSUE TITLE
How to send data with python interface

### ISSUE THREAD

**Issue by DavidLP** [eudaq/eudaq#412]
I'm on master and use the pybind11 interface. The example works, but I would like to know how to send actual data (a numpy array). How can I define the data type? Example:

```python
def RunLoop(self):
  while(self.is_running):
    ev = pyeudaq.Event("RawEvent", "sub_name")
    remaining_data = np.ndarray((0,), dtype=np.uint32)
    ev.AddBlock(0, remaining_data)  # Howto?
    self.SendEvent(ev)
```

The interface expects:
```python
self: pyeudaq.Event, index: int, data: std::vector<unsigned char, std::allocator<unsigned char> >
```

How to provide a python data container that can be auto converted to the STL container here?

**Comment by arummler** [comment]
I am not actually sure as I never used the wrapper but looking into the pybind docu:
http://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html
http://pybind11.readthedocs.io/en/stable/advanced/cast/index.html
I get the impresson we should include stl.h
Could you try that?

**Comment by DavidLP** [comment]
I added `#include "pybind11/stl.h"` to `PybindEvent.cc` and called:
```python
ev.AddBlock(1, [0, 0])
```

and still get
```bash
ERROR: CommandReceiver: User's RunLoop throws an exception 2018-02-26 08:45:39.107 [in /home/davidlp/git/eudaq/main/lib/core/src/CommandReceiver.cc:223, bool eudaq::CommandReceiver::RunLooping()]
Start of RunLoop in ExamplePyProducer
INFO: RUN #17 is to be stopped... 2018-02-26 08:45:40.530
DoStopRun
Caught exception: TypeError: AddBlock(): incompatible function arguments. The following argument types are supported:
    1. (self: pyeudaq.Event, index: int, data: std::vector<unsigned char, std::allocator<unsigned char> >) -> int

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

At:
  /home/davidlp/git/bdaq53/bdaq53/scans/ExamplePyProducer.py(48): RunLoop
```

**Comment by eyiliu** [comment]
fixed by PR #415 
The the AddBlock now accepts  data from python by bytes. The ExaamplePyProducer is also upgrade.

**Comment by DavidLP** [comment]
Thank you. I actually found out right now that including "#include "pybind11/stl.h"" seems to work (I did not check what is received though, might be jibberish). My recompilation somehow did not create a new libary when I tested it before...
I would very much appreciate if a stand alone python producer module could be created from the pybind11 module and uploaded to pypi. Then including this in python projects would be easy and this would be the proper "pythonic" way to do this. Otherwise one has to fight a lot of `cmake` hacks to make this producer work. For example we use Anaconda python that has a lite Qt5 version that does not allow compilation of the EuDaq gui. Root include also often fails. A stripped down python package without all the other eudaq stuff would be great.

**Comment by arummler** [comment]
If I understand it correctly including the header file translates all (nested) stl types automatically. Yi now included some explicite casting. I do not know which is better but somehow I would tend to the more generic solution offered by pybind11. 

What kind of cmake hacks do you mean? Qt is only required if the gui is to be built and root only for the stdeventmonitor (and some producers). Those can be simply activated/deactivated using ccmake.

**Comment by arummler** [comment]
Uploading to pypi sounds reasonable, someone would need to look into how to do it. Certainly it could be then included into the automatic binary release system using travis CI which I am tinkering with from time to time (unfortunately still under development).

**Comment by arummler** [comment]
Sure, I am just saying that you do not need to bother to provide Qt and root at all if you e.g. do not need the itk strip producer and the gui.

**Comment by DavidLP** [comment]
Yes, of cause. Since I am able to use the python producer now, I close this issue.
