### ISSUE TITLE
Time correlation plots not reset?

### ISSUE THREAD

**Issue by adavidzh** [eudaq/eudaq#424]
I was wondering if there is a reason why the "CorrelationVsTime" histograms are not reset upon Run Stop/Start.
Basically, the histograms are not extended from run to run (i.e. one cannot see all the runs) but they are overwritten without clearing, making things a little confusing because during one run, the data from previous runs is still displayed.

The fix, if deemed relevant, would be to add `_2dcorrTimeY->Reset()` and `_2dcorrTimeX->Reset()` to:
https://github.com/eudaq/eudaq/blob/587a201c414de7e4332c5cd7ff5445711855a147/monitors/onlinemon/src/CorrelationHistos.cc#L143-L146

**Comment by arummler** [comment]
Adding it for eudaq 1: 4edf51f605b4af352b92c4faca1401ee6129f8dc

**Comment by arummler** [comment]
Adding it for eudaq 2: 4edf51f605b4af352b92c4faca1401ee6129f8dc

**Comment by adavidzh** [comment]
Thanks!
