### ISSUE TITLE
nreader does not compile anymore

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#441]
Due to changes in general cmake it does not compile anymore:
- global includes missing
- not exported target

CMakeLists.txt of nreader needs rework to modern style as well.

**Comment by tbisanz** [comment]
Hey, is this related to: https://github.com/eutelescope/eutelescope/issues/383

**Comment by arummler** [comment]
Yes, that's the problem, I did not see it, thanks. Need rework or the nreader cmake file.

**Comment by arummler** [comment]
Fixed (hopefully) in v1.x-dev
