### ISSUE TITLE
[v1.7-dev] CMake error after pulling da9daff0361f

### ISSUE THREAD

**Issue by duartej** [eudaq/eudaq#446]
After a pulling of the branch v1.7-dev as today (da9daff0361f), when trying to configure with cmake and using
`cmake .. -DBUILD_tlu=ON -DBUILD_python=ON -DBUILD_ni=ON -DUSE_LCIO=ON -DBUILD_nreader=ON
`
Appears the following error
>CMake Error:
> export called with target "EUDAQ" which requires target
>  "DetectorDescriptons" that is not in the export set.
>
>  If the required target is not easy to reference in this call, consider
> using the APPEND option with multiple separate calls.

Note that previously the configuration and building was working perfectly fine (previously means  https://github.com/duartej/eudaq/tree/v1.7-dev, forking from cd5d9aed46c ) 

Maybe have you added anything I missed?

**Comment by arummler** [comment]
That's covered by issue #441 I started to implement proper config file export in cmake and as I do not regularly compile with nreader I missed to change that. I will try to fix it as soon as possible.

**Comment by arummler** [comment]
Should be fixed now, please try with v1.x-dev

**Comment by arummler** [comment]
@duartej Did you have opportunity to test it? Could you please make a PR for your bdaq53a related changes? The ITK pixel testbeam is going to start on Wednesday and they will be needed.

**Comment by duartej** [comment]
yes, I'm on it. I'm trying to cross-check as well some improvements we did (as the ability to add more than 1 board) and understand implications for the posterior reconstruction. I want to be sure to request you a merge which I don't have to patch later.

**Comment by duartej** [comment]
Ok, when trying to merge with the last commit of v1.x-dev, the following error is getting me annoyed:
```bash
[  6%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/plugins/DataConverterPlugin.cc.o
In file included from /eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/interfaces/pixel/include/EUTelTrackerDataInterfacerImpl.h:34:0,
                 from /eudaq/eudaq/main/lib/plugins/DataConverterPlugin.cc:7:
/eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/interfaces/pixel/include/EUTelTrackerDataInterfacerImpl.tcc: In instantiation of 'eutelescope::EUTelTrackerDataInterfacerImpl<PixelType>::EUTelTrackerDataInterfacerImpl(IMPL::TrackerDataImpl*) [with PixelType = eutelescope::EUTelGenericSparsePixel]':
/eudaq/eudaq/main/lib/plugins/DataConverterPlugin.cc:54:55:   required from here
/eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/interfaces/pixel/include/EUTelTrackerDataInterfacerImpl.tcc:20:43: error: call of overloaded 'make_unique()' is ambiguous
   auto pixel = std::make_unique<PixelType>();
                                           ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from /eudaq/eudaq/main/include/eudaq/Time.hh:7,
                 from /eudaq/eudaq/main/include/eudaq/Serializer.hh:9,
                 from /eudaq/eudaq/main/include/eudaq/Event.hh:11,
                 from /eudaq/eudaq/main/include/eudaq/StandardEvent.hh:4,
                 from /eudaq/eudaq/main/include/eudaq/DataConverterPlugin.hh:4,
                 from /eudaq/eudaq/main/lib/plugins/DataConverterPlugin.cc:1:
/usr/include/c++/5/bits/unique_ptr.h:764:5: note: candidate: typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = eutelescope::EUTelGenericSparsePixel; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<eutelescope::EUTelGenericSparsePixel, std::default_delete<eutelescope::EUTelGenericSparsePixel> >]
     make_unique(_Args&&... __args)
     ^
In file included from /eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/libraries/include/EUTELESCOPE.h:53:0,
                 from /eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/interfaces/pixel/include/EUTelTrackerDataInterfacerImpl.h:13,
                 from /eudaq/eudaq/main/lib/plugins/DataConverterPlugin.cc:7:
/eudaq/ilcsoft/v01-19-02/Eutelescope/master/eutelescope/libraries/include/make_unique.h:12:22: note: candidate: std::unique_ptr<_Tp> std::make_unique(Args&& ...) [with T = eutelescope::EUTelGenericSparsePixel; Args = {}]
   std::unique_ptr<T> make_unique(Args &&... args) {
                      ^
main/lib/CMakeFiles/EUDAQ.dir/build.make:1670: recipe for target 'main/lib/CMakeFiles/EUDAQ.dir/plugins/DataConverterPlugin.cc.o' failed
make[2]: *** [main/lib/CMakeFiles/EUDAQ.dir/plugins/DataConverterPlugin.cc.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'main/lib/CMakeFiles/EUDAQ.dir/all' failed
make[1]: *** [main/lib/CMakeFiles/EUDAQ.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by duartej** [comment]
I tested over a fresh clone of the repository with the v1.x-dev branch and the problem is there: 
My system: ubuntu 16.04
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9)
cmake version 3.5.1

Could you confirm @arummler that the system requirements did not change?

**Comment by duartej** [comment]
Ok, I found the problem, it turns out that EUTelescope (I'm compiling with LCIO and EUTelescope) defines their own make_unique but I was not using the last commit of the package. 

Now, I facing this error: 
```bash
[ 73%] Linking CXX executable EURunsplitter.exe
input_line_10:12:10: fatal error: 'include/OnlineMonWindow.hh' file not found
#include "include/OnlineMonWindow.hh"
         ^
Error: /rootfr/root/bin/rootcling: compilation failure (/eudaq/eudaq/build/monitors/onlinemon/libOnlineMonDictcb0b6bed6c_dictUmbrella.h)
monitors/onlinemon/CMakeFiles/OnlineMon.exe.dir/build.make:61: recipe for target 'monitors/onlinemon/OnlineMonDict.cxx' failed
make[2]: *** [monitors/onlinemon/OnlineMonDict.cxx] Error 1
CMakeFiles/Makefile2:2040: recipe for target 'monitors/onlinemon/CMakeFiles/OnlineMon.exe.dir/all' failed
make[1]: *** [monitors/onlinemon/CMakeFiles/OnlineMon.exe.dir/all] Error 2
```

**Comment by arummler** [comment]
An non-stl implementation of make_unique - I hope it is removed in the newest version. The error with the include I have already seen, a bit strange. Which root version are you using?

**Comment by duartej** [comment]
ROOT 6.10/02
I fixed it by adding the absolute path in the onlinemon/CMakeLists.txt 
```cmake 
SET(OnlineMon_HEADERS 
  ${CMAKE_CURRENT_SOURCE_DIR}/include/OnlineMonWindow.hh
  ... 
```
But then, an different error appears:
```bash
[ 76%] Generating OnlineMonDict.cxx, libOnlineMonDict_rdict.pcm, libOnlineMonDict.rootmap
In file included from input_line_10:12:
In file included from /eudaq/eudaq/monitors/onlinemon/include/OnlineMonWindow.hh:36:
/eudaq/eudaq/monitors/onlinemon/include/OnlineMon.hh:15:10: fatal error: 'eudaq/Configuration.hh' file not found
#include "eudaq/Configuration.hh"
         ^
Error: /rootfr/root/bin/rootcling: compilation failure (/eudaq/eudaq/build/monitors/onlinemon/libOnlineMonDict425915fdea_dictUmbrella.h)
monitors/onlinemon/CMakeFiles/OnlineMon.exe.dir/build.make:72: recipe for target 'monitors/onlinemon/OnlineMonDict.cxx' failed
make[2]: *** [monitors/onlinemon/OnlineMonDict.cxx] Error 1
```
which looks like the proper include directories are not passed to the ROOT_GENERATE_DICTIONARY

**Comment by duartej** [comment]
OK, this is fixed if you change in the onlinemon CMakeList.txt:
```bash
#include_directories(${OnlineMon_EUDAQ_HEADERS})
include_directories("${CMAKE_SOURCE_DIR}/main/include")
```
probably there is a more elegant way to do it using the target_include_directories but...

**Comment by duartej** [comment]
Ok, I just checked the code and it seems to work, so I will ask for the pull request, where I will include the previous fixes we just discussed

**Comment by arummler** [comment]
I thought that I had fixed it with:

> #This is an ugly workaround...should be all automatically done by the dictionary macro from root
get_target_property(OnlineMon_EUDAQ_HEADERS EUDAQ INCLUDE_DIRECTORIES)
#message(${OnlineMon_EUDAQ_HEADERS})
include_directories(${OnlineMon_EUDAQ_HEADERS})

which is also not a nice way to do it. I does not help that root cmake is getting better and thus taking care of all root versions is difficult.
