### ISSUE TITLE
EUDET TLUProducer: Is this incrementing correct?

### ISSUE THREAD

**Issue by dreyling** [eudaq/eudaq#449]
https://github.com/eudaq/eudaq/blob/98ad0387e9f82d875b9f09b5a6e233267a02631e/user/eudet/module/src/TluProducer.cc#L108

or should it be i++? Then it would take the first TLU trigger with ID 0 for the first EUDAQ event, right?

**Comment by duartej** [comment]
Both cases produce the same output, take a look here: https://stackoverflow.com/questions/4706199/post-increment-and-pre-increment-within-a-for-loop-produce-same-output

**Comment by dreyling** [comment]
Thanks, right, I was checking it also...
