### ISSUE TITLE
[v1.x-dev] CMAKE language definition prevents compilation for version 1.9 and above

### ISSUE THREAD

**Issue by DavidLP** [eudaq/eudaq#466]
The CMAKE project language has been fixed to `CXX` in [this](https://github.com/eudaq/eudaq/commit/763eddd3f33a30ff87d1e277d2422055dd9aa9fa) commit. Before it was undefined, thus `C` was also used. When compiling EUDAQ versions specifying `CXX` (1.9 and above) I get the following error:

```bash
-- Looking for include file pthread.h
CMake Error at /usr/local/share/cmake-3.2/Modules/CheckIncludeFiles.cmake:74 (try_compile):
  Unknown extension ".c" for file

    /home/davidlp/git/eudaq/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX

  See project() command to enable other languages.
```

Not specifying the language fixes this bug.

- System: Ubuntu 14.04.5 LTS
- GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
- CMAKE version 3.2.2

**Comment by arummler** [comment]
With cmake 3.9 and higher I do not observe this. Could you try to update your cmake version?

**Comment by arummler** [comment]
One can also add C as a language but if remember correctly I had a reason not do to it... Wondering where CheckIncludeFiles.c comes from.

**Comment by DavidLP** [comment]
I try with newer CMAKE and report back to you

**Comment by DavidLP** [comment]
Ok, with `CMAKE 3.11` it works. Not sure if you want to specify such a new version. Last [Ubuntu LTS](https://launchpad.net/ubuntu/xenial/+source/cmake) has `CMAKE 3.5`.

**Comment by arummler** [comment]
removed it again in 4192c9c4861e648b6ccfeb48e2b3e68e9ae505ab
