### ISSUE TITLE
[v2-OS X] Typo in RunControl function ReadInitialiseFile

### ISSUE THREAD

**Issue by msohailamjad** [eudaq/eudaq#468]
It's strange that when I use ReadInitiliseFile() function in RunControl, it works and when I tried to correct it to ReadInitializeFile(), it caused problems. [Note the difference between Initilise and InitiAlise of missing 'A']. The error caused was a dyanmic library linking error on OS X. Here is the print: 
  Fail to load module binary (libeudaq_module_std.dylib) 2018-07-03 19:51:16.083
A dynamic linking error occurred: (dlopen(libeudaq_module_std.dylib, 2): Symbol not found: __ZN5eudaq10RunControl17ReadInitilizeFileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  Referenced from: eudaq/lib/../lib/libeudaq_module_std.dylib
  Expected in: eudaq/bin/../lib/libeudaq_core.2.0.dylib
 in eudaq/lib/../lib/libeudaq_module_std.dylib)

**Comment by arummler** [comment]
Could you try to delete your build directory and build from scratch? Often this type of error is due to a mix of old and new binary (it does not recognise what it needs to recompile properly).

**Comment by msohailamjad** [comment]
I already did that to no effect.

**Comment by arummler** [comment]
There could be a new typo as
it was Initilise
you wanted Initialize
and it searches for Initilize

**Comment by msohailamjad** [comment]
Thank you for pointing out, but actually I kept it as Initialise (with an 's' - ignore my typo of using 'z' for reporting the issue, please). 
 I have removed the libeudaq_module_std and re-complied from scratch, it works smoothly (with ReadInitialiseFile() this time).
