### ISSUE TITLE
Possible bug in /eudaq/main/lib/core/src/Producer.cc

### ISSUE THREAD

**Issue by PaoloGB** [eudaq/eudaq#474]
There seems to be a bug introduced by a recent commit (I think 65dda9e814a04a96de1e8d9d2d44436f530a1a56 but not completely sure at this stage).

While euRun is running, if I instantiate a producer with  
`./euCliProducer -n FmctluProducer -t fmctlu`
I get a message 

`Offline run :`
` CLI Run Check: 1`

but nothing else happens: the producer does not appear in the list of connections and no action is available.

**Comment by dreyling** [comment]
@msohailamjad can you please check the functionality of your changes for the standard operation with euRun? This example should work: https://github.com/eudaq/eudaq#execution

I have created a tag 2.1.1 which is before this implementation and works out-of-box: 
https://github.com/eudaq/eudaq/commit/1a706ce61a21f7720585a96ed4f3c2d5705b5c76

**Comment by msohailamjad** [comment]
@PaoloGB and @dreyling 
 The default way to start an offline run is by leaving the port option for RunControl empty. If you can give the RunControl address while running, Producer should connect to RC ( specify -r option i.e.). 
 See the following for details: 
 eudaq::Option<std::string> rctrl(op, "r", "runcontrol", "", "address",
				   "The address of the run control to connect to");
  op.Parse(argv);
  std::string rctrl_value = rctrl.Value();
  if(!rctrl_value.empty()) std::cout << "Online run, RC is at :  " << rctrl_value << std::endl;
  else if(rctrl_value.empty()) std::cout << "Offline run : " << rctrl_value << std::endl;

Paolo! Can you give it a try, please?

**Comment by dreyling** [comment]
@msohailamjad no, it is not working: I have just tried to connect only the euLog, and it is not working, see attachment
![screenshot from 2018-07-26 19-14-07](https://user-images.githubusercontent.com/10775275/43277489-7dd9e5ee-9108-11e8-9dd6-4614f116ced2.png)
.
Can you please fix that and test always with the working example https://github.com/eudaq/eudaq#execution, otherwise we should revert to the working tag v2.1.1, since we have other developments in the pipeline?

**Comment by msohailamjad** [comment]
I need to check in more detail.  I will get back to you when I find the problem. 
<img width="1207" alt="screen shot 2018-07-26 at 18 37 02" src="https://user-images.githubusercontent.com/25708987/43278545-5907dfb4-9103-11e8-9e1d-5638a6604a25.png">

**Comment by dreyling** [comment]
I have reverted now the master branch, and will add the ttree tomorrow, which looks fine. For the psarun, we have to check more in detail.
