### ISSUE TITLE
Running Online Monitor over a file (in offline mode)

### ISSUE THREAD

**Issue by andreypz** [eudaq/eudaq#499]
Hello,
In the previous version of eudaq (v1.7) it was possible to re-run the online monitor over a raw data file, via "onlineMon.exe -f data.raw".
In the new version (v2.0) this possibility is removed. 
Is there is another way to re-run the online monitor code offline? For example, there is `-o` option, but it does not seem to work.

**Comment by dreyling** [comment]
Hi Andrey, well spotted, yes, so far we didn't find the time to migrate this offline option. 
If you want to have a first quick look into the raw data, you can use the command line tools, euCliReader, euCliTriggerReader, ...

**Comment by eyiliu** [comment]
Hello,
I have a branch which re-enable the offline monitor.  However, it is not yet well tested.
https://github.com/eyiliu/eudaq/tree/monitor-offline

**Comment by dreyling** [comment]
Can we close this with this https://github.com/eudaq/eudaq/pull/526 ?

**Comment by eyiliu** [comment]
Yes, closed.
