### ISSUE TITLE
Runtime dependencies on *all* module libraries

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#529]
I'm trying to compile a program, linking `libeudaq_core` in order to use the FileReader to decode event data recorded with EUDAQ. However, the factory does seem to create a run-time dependency on all module libraries `libeudaq_module_*` which were present when building - even those which are not even in the data file.

In addition, many of the modules seem to come with their own runtime dependencies which (I presume) are only necessary for actual data taking. Most notably, this is `libeudaq_module_tlu` which depends on `cactus_uhal` at runtime.

Is there a way around this?

**Comment by simonspa** [comment]
@jekroege for reference

**Comment by eyiliu** [comment]
We can only presume all the _libduaq_module*_ can link and work well with their own dependencies.
Load all mouldes during the runtime should be fine even if they are not called for a specific run. Even if a failure occors for a moulde loading,  it will not affect the loading of the remaining ones.

Regarding to tlu module, a better practice can be to have a cmake option which turns off the build of producer code if we can not figure out a way to link cactus_uhal lib for the tlu producer.

To have RPATH with cactus_uhal path is also a good way.

**Comment by eyiliu** [comment]
To be closed, it there is no further discussion.
