### ISSUE TITLE
Clang does not like auto in function prototypes

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#533]
> In file included from /Users/travis/build/eudaq/eudaq/gui/src/euRun.cxx:4:
> /Users/travis/build/eudaq/eudaq/gui/include/euRun.hh:49:25: error: 'auto' not allowed in function prototype
> bool addStatusDisplay(auto connection);
>
>                        ^~~~
>
>/Users/travis/build/eudaq/eudaq/gui/include/euRun.hh:50:28: error: 'auto' not allowed in function prototype
>
 > bool removeStatusDisplay(auto connection);

**Comment by lhuth** [comment]
This feature is available from  c++14 on. 
Are there any plans to require a newer c++ version as eudaq2 is rather new (c++11 is stated in the readme)? If not I would change the code.
