### ISSUE TITLE
Question: what platforms and architectures can EUDAQ run on currently?

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#535]
This question concerns mostly EUDAQ1, as I need the info for the publication currently in preparation: I know that EUDAQ runs on and is supported on recent versions of GNU/Linux, Apple OSX and Microsoft Windows on i686 systems -- but has it recently been tested on other platforms or architectures?

It used to support PowerPC, is that still supported? Has anyone tried ARM (e.g. on a Raspberry Pi)?
How about FreeBSD or similar?

Any info would be much appreciated! :)

**Comment by eyiliu** [comment]
The main thing to concern is the CPU endianness.  The PowerPC is big-endian while x86 is little-endian. 
If the  big-endian PowerPC was supported before as you said, I believe it is still supported by the EUDAQ1's core.  However, you must have a look if your Producer and ConverterPlugin are taking care of the endianness.

**Comment by arummler** [comment]
My CI is unfortuantely in the moment not complete but there is one RPi producer which is quite current.

**Comment by simonspa** [comment]
I'm running my EUDAQ producer on a Xilinx Zynq ZC706 board, i.e. on an `armv7l` 32-bit ARM-architecture SoC. I have a recipe to compile it using our build system (Yocto).
