### ISSUE TITLE
"connection refused" when connect producer to runController

### ISSUE THREAD

**Issue by ZihengChen** [eudaq/eudaq#549]
We are experiencing a connection rejection issue when trying to connect ExampleProducer on one pc to runController on the other pc.

## Describe of Setup
We are using EUDAQ `V1.9.1`. Our setup is the following
- `runController pc` has *runController, runLog, dataCollector and TLUProducer*. They are started with the following [scripts](https://gitlab.cern.ch/zichen/bcm1f_testbeam/blob/master/Producer/eudaq/etc/scripts/STARTRUN.brilRunController). Its IP address is *128.141.58.193*. Firewalls is stopped and relevant ports are open.

- `producer pc` has *ExampleProducer*, started by command `ExampleProducer.exe -r tcp://128.141.58.193:44000`. Firewalls is stopped and relevant ports are open.

## Describe of Connection Issue
Upon start the programs on `runController pc` and `producer pc`, the following issue is encountered . 

On the `runController pc`, the runController gui successfully displays ExampleProducer and the IP+port of ExampleProducer. However on the `producer pc`, the following message is printed in terminal

```
Command Thread exiting due to exception:
Connection refused
  From /afs/cern.ch/user/z/zichen/public/test/eudaq/main/lib/src/TransportTCP.cc:575
  In void eudaq::TCPClient::OpenConnection()
```
And ExampleProducer cannot be initialized from runController.

## Extra Information

1. If running ExampleProducer on the same pc as runController, there is no such issue about connection refused. ExampleProducer can be initialized and configured successfully.

2. on `producer pc`, telnet shows runController is actually listening at `128.141.58.193:44000`

3. on `runController pc`, wireShark shows the internet traffic but it seems to give no clue about refused connection. A screen shoot of wireShark outputs is attached.

4. Ports are checked in `Open` status on both PCs.

Let me know if you have any idea about the cause and solution for this issue.

Many thanks

Ziheng

![Screenshot](https://user-images.githubusercontent.com/13590259/55962906-129fcb00-5c72-11e9-98d1-6edf202177ee.png)

**Comment by dreyling** [comment]
As discussed in the test beam hut, truly the HOSTNAME-environment variable has to be set on the RunControl machine: `export HOSTNAME=<local IP>`
