### ISSUE TITLE
[v1.x-dev] Simple example segfaults

### ISSUE THREAD

**Issue by DavidLP** [eudaq/eudaq#564]
I just compiled the actual `v1.x-dev` version (https://github.com/eudaq/eudaq/commit/324f5e90389135790f94f0917dda40cf2b97a6c6) and:

1. Start `euRun.exe`
2. Start `TestProducer.exe`

and get

```bash
davidlp@silab47:~/git/eudaq/bin$ ./euRun
terminate called after throwing an instance of 'eudaq::LoggedException'
  what():  Deserialize asked for 4, only have 0
  From /home/davidlp/git/eudaq/main/lib/core/src/BufferSerializer.cc:20
  In virtual void eudaq::BufferSerializer::Deserialize(unsigned char*, std::size_t)
Aborted (core dumped)
```

Any idea why?

**Comment by arummler** [comment]
I just tried it with a freshly compiled version on Ubuntu 19.10 and could not provoke the behaviour. For me everything works fine. Which OS are you using? Could you run it through gdb?

**Comment by arummler** [comment]
Wait a second: "main/lib/core/src" is the directory structure from eudaq2.  Did you already build eudaq2? Might be that the binaries were not completely cleaned up in-between.

**Comment by DavidLP** [comment]
Good point. Yes some time ago I tried Eudaq2. I will clean up properly and try again. Thank you.

**Comment by DavidLP** [comment]
Ok, with a fresh checkout it works. THX
