### ISSUE TITLE
Light-weight installation for reconstruction?

### ISSUE THREAD

**Issue by jekroege** [eudaq/eudaq#572]
It would be very useful to have something like a light-weight installation of eudaq2 that only compiles the `StandardEvent converters`.

The problem I'm facing:
When I'm running my reconstruction using `corryvreckan`, I need a full installation of eudaq2 to be linked against which means that I also need to install `cactus` and all the other packages which are needed for the TLU for instance.
However, these packages should only be required when actually taking data with eudaq, not to compile the converters.

This also makes it particularly complicated to get the reconstruction (with corryvreckan) to run on a new PC as I have to install many many packages.

**Comment by jekroege** [comment]
It would be very useful to have something like a light-weight installation of eudaq2 that only compiles the `StandardEvent converters`.

The problem I'm facing:
When I'm running my reconstruction using `corryvreckan`, I need a full installation of eudaq2 to be linked against which means that I also need to install `cactus` and all the other packages which are needed for the TLU for instance.
However, these packages should only be required when actually taking data with eudaq, not to compile the converters.

This also makes it particularly complicated to get the reconstruction (with corryvreckan) to run on a new PC as I have to install many many packages.

**Comment by lhuth** [comment]
Hi @jekroege,
thanks for pointing that out. 

The desired behaviour is already implemented: If you set `USER_TLU_BUILD=ON` the converter will be build even if the external dependencies (`cactus`, `ZestSC1` and `libusb`)are not found. 

However the cmake output is misleading and we should change that as discussed online.

**Comment by jekroege** [comment]
All done, see MR #573

**Comment by eyiliu** [comment]
Thanks @jekroege for #573
