### ISSUE TITLE
Way to determine detector from RaqDataEvent?

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#576]
We need a way to determine the detector data contained in a UEDAQ2 RawDataEvent, preferrably before decoding. However, there does not seem to be a coherent way to do so.

As far as I can see, we have the following information available:

```cpp
auto my_raw_event = std::make_shared<eudaq::Event>();
// Returns name of the raw event type the factory is registered with, e.g. "NiRawData"
// The type we get here does not correspond to the detector (M26) and is confusing
//  to users - because normally they don't have to deal with these "EUDAQ2-internal"
// names
std::cout << my_raw_event->getDescription() << std::endl;

auto my_std_event = std::make_shared<eudaq::StandardEvent>();
eudaq::StdEventConverter::Convert(my_raw_event, my_std_event);
// Still the same cryptic name
std::cout << my_std_event->getDescription() << std::endl; 

// For events without planes, here we are stuck (e.g. TLU) there is no way to query
// anything in the event that would return "tlu".

// For other events, we can loop over all planes:
for(size_t i_plane = 0; i_plane < my_std_event->NumPlanes(); i_plane++) {                                                                        
    auto plane = my_std_event->GetPlane(i_plane);
    // Now we finally get something that looks like an identifier for the detector
    std::cout << plane.Sensor() << std::endl;
    // - but there might still be multiple planes, so let's check
    std::cout << plane.ID() << std::endl;
    // which is just an enumerator as it seems.
}
```

Could we somehow provide a better interface for other software? We need to be ab;le to determine which detectors are stored in a raw event to select which events we should be taking into account for the reconstruction.

**Comment by simonspa** [comment]
@jekroege

**Comment by lhuth** [comment]
Hi @simonspa,

Sorry for the rather late feedback - been on holidays.

The naming is somewhat unfortunate, I agree. However, changing this disables reading old telescope data. 

RawEvents do not know what data they contain - it's simply blocks and a very basic header.  

In your above example, you are converting an `Event` to a `StandardEvent`. The converison only "unpacks" the data blocks and adds this information. I think this could be rather simply improved by adding something like `StandardEvent->SetDetector(std::string name)` and  `StandardEvent->GetDetector()`. As the converters can interpret the blocks, they could set this name. However, this assumes, that only one type of detector is stored in an event, which is maybe not always the case. And it also requires event conversion first, which slows down reading.

We are open for better ideas.

**Comment by simonspa** [comment]
Hej @lhuth - hope you enjoyed the holidays... :)

The issue here is the conversion in Corryvreckan (or any other flexible code for event building of EUDAQ2, for that) If we want to be flexible and support events synched based on TriggerID, EventID or not synched at all (completely separate DataCollectors) we need to be able to select which sections of a file (i.e. which events or sub-events) to process and which ones to ignore. The relevant discussion from the reconstruction side is summarized here: https://gitlab.cern.ch/corryvreckan/corryvreckan/merge_requests/145#note_2793202 (and the rest of the MR discussion, too)

**Comment by simonspa** [comment]
After discussing in above mentioned MR we decided to implement a new member to StdEvent to describe the type of detector contained. The StdEvent converters should set this via `void SetDetectorType(std::string type)` and it is publicly accessible via `std::string GetDetectorType() const`.

**Comment by eyiliu** [comment]
PR #578 merged.
