### ISSUE TITLE
Release new EUDAQ2 version

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#579]
With the interface becoming more mature for flexible offline event building (see MR #578, #532, #562 etc) it would be nice to have a released & tagged version of EUDAQ2 which can be checked for in external software.

Currently there is no way to check if a certain feature set is available in the distributed EUDAQ2 package or not apart from attempting a build and failing in concluding it.

**Comment by eyiliu** [comment]
tag v2.3.0  created.
