### ISSUE TITLE
Scanning Feature: eventCounter required

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#584]
Even when running a time-based, the scanning component of RCGui requires a setting called `eventCounter`. From reading the code I can only infer that this seems to be the place to look for the current event number - but it's neither documented anywhere nor does it seem to be required for time-based scans.

We simply set 

```toml
[0]
eventCounter = 0
```

and it seem to work fine.

**Comment by lhuth** [comment]
Hi @simonspa ,
it is documented:
https://github.com/eudaq/eudaq/blob/master/gui/README.md
However, it is not needed to perform a time-based scan, as stated in the README - Therefore I would still consider it a bug. It's on my toDo list

**Comment by lhuth** [comment]
I think we can close this PR
