### ISSUE TITLE
Unable to link individual modules

### ISSUE THREAD

**Issue by simonspa** [eudaq/eudaq#596]
After merging of ffd2e4a110d743ceaeb1d91c64d18f45e0766acb I am left with no option to link against individual modules. I found this quite convenient when only working with an individual detector.

Any reason for not just leaving it there? You don't have to use it if you don't want to/don't need it.

**Comment by eyiliu** [comment]
-  With the 'export',  build against the eudaq will ask the dependencies of the enabled modules.
-  the 'export' of module is not required by eudaq.  

Therefore,  I guess the removing the 'export' is not bad idea in generally.

For the case some other software wants to link to the eudaq and also a specific module, this module can be set to 'export' by its module developer.  However, more 'export', more dependencies, and possibly more trouble.
