### ISSUE TITLE
Extend size of vectors handled by Serializer

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#65]
The serialization code casts the size of any vector or map being serialized onto an ```unsigned``` and writes this value into the data stream; since the new data format described in #37 will reserve 64-bit to store the length of meta data and data blocks, we should extend this in the serializer accordingly -- however, this would break binary compatibility e.g. with existing files. A verified versioning of (raw) files would therefore be useful *or* the change needs to be thoroughly documented (e.g. along side the release of 2.0).

Furthermore, a check that we do not lose data by casting onto a smaller width variable should be implemented!

**Comment by eyiliu** [comment]
The AIDAQ meta-data is not  the plan again.  But the unsigned (int), which is usually 32-bits, is OS/Arch  depending.  Change it to uint32_t or uint64_t might be better.

**Comment by arummler** [comment]
I think it is good practice in general (particularly since C++11) only to use machine independent types from <cstdint>. Probably we should state it as a goal to refactor accordingly.

**Comment by eyiliu** [comment]
Agree, close that AIDAQ meta issue. A new generic issue of "machine independent types" should be opened.
