### ISSUE TITLE
(FATAL) [R:EventLoaderEUDAQ2:TLU_0] Fatal internal error

### ISSUE THREAD

**Issue by chenzhl2018** [eudaq/eudaq#680]
Hi，
When I run eudaq2 corry, there is one problem below:
I use the data from BTTB10 tutorial slides, how can I do to deal with it?
Thanks in advance.

Factory<0x7f122c08aa98>:  Unknown class ID: <3634980144>
Factory<0x7f122c08aa98>:  Unknown class ID: <3634980144>
Factory<0x7f122c08aa98>:  Unknown class ID: <3634980144>
Factory<0x7f122c08aa98>:  Unknown class ID: <3634980144>
Factory<0x7f122c08aa98>:  Unknown class ID: <3634980144>
|15:25:30.485|   (FATAL) [R:EventLoaderEUDAQ2:TLU_0] Fatal internal error
                                                        Error reading from file '/ustcfs2/zchen/test/bttb10_tutorial_corryvreckan2/data/03_data_desy/run000715_ni_cut.raw': too many failed attempts (reading 0 bytes)
                                                       From /ustcfs2/zchen/test/eudaq/main/lib/core/src/FileDeserializer.cc:78
                                                       In std::size_t eudaq::FileDeserializer::FillBuffer(std::size_t)
                                                     Cannot continue...

**Comment by lhuth** [comment]
Hi @chenzhl2018 ,

The error message appears if you have an unknown datastream (triggered by a class id that has no matching data converter). Most likely you have not enabled the `TLU` in eudaq. You can do so by `cmake -D USER_TLU_BUILD=ON <paht-to-cmake>`. 

Let us know if it worked out this way :)

Cheers,
Lennart

**Comment by simonspa** [comment]
Hi @lhuth - yes the "Unknown class" is from a missing module, but the `FillBuffer` rather looks like a corrupt file, that's much deeper than a missing decoder module, that's file deserialization.

**Comment by chenzhl2018** [comment]
Hi,
Thank you for your reply！
I have enabled the TLU in eudaq before，but I can't install the spidr because I don't have an account to download spidr. I don't know if this is the wrong reason.
How should I do next？
Thanks.

[zchen@ui01 build]$ cmake ..
CMake Warning (dev) at CMakeLists.txt:1 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Determined EUDAQ version v2.5.2-7-g3db306e3
-- lib/lcio library is NOT to be built (EUDAQ_LIBRARY_BUILD_LCIO=OFF)
-- lib/ttree is NOT to be built (EUDAQ_LIBRARY_BUILD_TTREE=OFF)
-- doc/manual is NOT to be built (EUDAQ_BUILD_MANUAL=OFF)
-- doc/doxygen is NOT to be built (EUDAQ_BUILD_DOXYGEN=OFF)
-- GUIs of executables (euRun, euLog) are NOT to be built (EUDAQ_BUILD_GUI=OFF)
-- monitor/StdEventMonitor is NOT to be built (EUDAQ_BUILD_STDEVENT_MONITOR=OFF)
-- monitor/ROOTMonitor is NOT to be built (EUDAQ_BUILD_ONLINE_ROOT_MONITOR=OFF)
-- user/example is to be built (USER_EXAMPLE_BUILD=ON)
-- user/experimental is NOT to be built (USER_EXPERIMENTAL_BUILD=OFF)
-- user/eudet is to be built (USER_EUDET_BUILD=ON)
-- Building device euCliMergerMixedCombinedTrigID
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliMergerMixedCombinedTrigID.cxx
-- Building device euCliMergerMixedDuplicateMimosaEvtID
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliMergerMixedDuplicateMimosaEvtID.cxx
-- Building device euCliMergerMixedDuplicateMimosaTrigID
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliMergerMixedDuplicateMimosaTrigID.cxx
-- Building device euCliMergerStandardEvtID
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliMergerStandardEvtID.cxx
-- Building device euCliMergerStandardTrigID
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliMergerStandardTrigID.cxx
-- Building device euCliTeleReader
-- Building file /ustcfs2/zchen/test/eudaq/user/eudet/exe/src/euCliTeleReader.cxx
-- user/calice is NOT to be built (USER_CALICE_BUILD=OFF)
-- user/caribou is to be built (USER_CARIBOU_BUILD=ON)
-- user/cmspixel is NOT to be built (USER_CMSPIXEL_BUILD=OFF)
-- user/itkstrip is NOT to be built (USER_ITKSTRIP_BUILD=OFF)
-- user/timepix3 is to be built (USER_TIMEPIX3_BUILD=ON)
-- Looking for SPIDR...
-- -- SPIDR include at SPIDR_INCLUDE_DIR-NOTFOUND -- Found
-- -- SPIDR library at SPIDR_LIB-NOTFOUND -- Found
-- Could not find SPIDR, make sure all necessary components are compiled and that the variable SPIDRPATH points to the installation location:

	$ export SPIDRPATH=/your/path/to/SPIDR

 (missing: SPIDR_LIB SPIDR_INCLUDE_DIR) 
-- Timepix3 StandardEvent converter will be built
CMake Warning at user/timepix3/module/CMakeLists.txt:16 (MESSAGE):
  Timepix3 Producer NOT built: SPIDR, ROOT and/or Xerces-C are missing


-- user/tlu is to be built (USER_TLU_BUILD=ON)
-- No CACTUS/uhal header: AIDA TLU Producer is NOT to be built. Please refer to the documentation on how to obtain the software. Converter will be built anyway.
-- Could not find ZestSC1 driver package required by tlu producer. Please refer to the documentation on how to obtain the software. Converter will be built anyway.
-- Checking for module 'libusb'
--   No package 'libusb' found
-- Could not find tlu firmware package required by tlu producer. Please refer to the documentation on how to obtain the software.
-- EUDET TLU stand-alone executables are NOT to be built (USER_BUILD_EUDET_TLU=OFF)
-- user/stcontrol is NOT to be built (USER_STCONTROL_BUILD=OFF)
-- user/aidastrip is NOT to be built (USER_AIDASTRIP_BUILD=OFF)
-- user/tbscDESY is NOT to be built (USER_TBSCDESY_BUILD=OFF)
-- user/MuPix8 is NOT to be built (USER_MuPix8_BUILD=OFF)
-- user/piStage is NOT to be built (USER_PISTAGE_BUILD=OFF)
-- user/ITS3 is NOT to be built (USER_ITS3_BUILD=OFF)
-- user/cms-phase2 is NOT to be built (USER_CMSPHASE2_BUILD=OFF)
-- CMAKE_BINARY_DIR: /ustcfs2/zchen/test/eudaq/build
-- PROJECT_SOURCE_DIR: /ustcfs2/zchen/test/eudaq
-- This is CMake 3.20.0 (/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc11-opt/bin/cmake) running on Linux (3.10.0-1127.8.2.el7.x86_64 "CentOS Linux release 7.8.2003 (Core)")
-- 64-bit compiler detected
-- Using Clang (/cvmfs/sft.cern.ch/lcg/releases/clang/12.0.0-8916b/x86_64-centos7/bin/clang++) version 12.0.0
-- Compiler Flags:   -std=c++17 -pipe -fsigned-char -pthread 
-- With COMPILE_DEFINITIONS = EUDAQ_PLATFORM=PF_LINUX;EUDAQ_FUNC=__PRETTY_FUNCTION__ 
-- Check your configuration/flags with: cmake -L
-- Configuring done
-- Generating done
-- Build files have been written to: /ustcfs2/zchen/test/eudaq/build

**Comment by simonspa** [comment]
SPIDR is not necessary since it's only the DAQ component, the converter should be build anyway:

```
 -- Timepix3 StandardEvent converter will be built
```

**Comment by chenzhl2018** [comment]
Is this the reason?

> -- Checking for module 'libusb'
-- No package 'libusb' found
-- Could not find tlu firmware package required by tlu producer. Please refer to the documentation on how to obtain the software.
-- EUDET TLU stand-alone executables are NOT to be built (USER_BUILD_EUDET_TLU=OFF)

**Comment by simonspa** [comment]
No, as said this is not a missing module issue, but to me it looks like the input file is corrupt.

The TLU converters are built, check below:

```
-- No CACTUS/uhal header: AIDA TLU Producer is NOT to be built. Please refer to the documentation on how to obtain the software. Converter will be built anyway.
-- Could not find ZestSC1 driver package required by tlu producer. Please refer to the documentation on how to obtain the software. Converter will be built anyway.
```

**Comment by chenzhl2018** [comment]
You mean the data is corrupt?
I use the data from
git clone https://gitlab.cern.ch/ffeindt/bttb10_tutorial_corryvreckan.git.

**Comment by chenzhl2018** [comment]
This is the front part of the running result.

```
Error in <TExMap::Add>: key 139625328156448 is not unique
|17:29:00.226|  (STATUS) Loading module EventLoaderEUDAQ2
|17:29:00.232|    (INFO) [C:EventLoaderEUDAQ2:TLU_0] Setting EUDAQ2 log level to "ERROR"
|17:29:00.233|  (STATUS) Loading module EventLoaderEUDAQ2
|17:29:00.233|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_0] Setting EUDAQ2 log level to "ERROR"
|17:29:00.233|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_1] Setting EUDAQ2 log level to "ERROR"
|17:29:00.233|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_2] Setting EUDAQ2 log level to "ERROR"
|17:29:00.233|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_3] Setting EUDAQ2 log level to "ERROR"
|17:29:00.234|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_4] Setting EUDAQ2 log level to "ERROR"
|17:29:00.234|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_5] Setting EUDAQ2 log level to "ERROR"
|17:29:00.234|  (STATUS) Loading module EventLoaderEUDAQ2
|17:29:00.235|    (INFO) [C:EventLoaderEUDAQ2:Timepix3_0] Setting EUDAQ2 log level to "ERROR"
|17:29:00.239|  (STATUS) Loaded 17 module instances 
|17:29:00.239|  (STATUS) =================| Initializing modules |==================
|17:29:00.329|  (STATUS) [I:EventLoaderEUDAQ2:MIMOSA26_0] Initializing "EventLoaderEUDAQ2:MIMOSA26_0"^Z

```

**Comment by chenzhl2018** [comment]
> Hi @chenzhl2018 ,
> 
> The error message appears if you have an unknown datastream (triggered by a class id that has no matching data converter). Most likely you have not enabled the `TLU` in eudaq. You can do so by `cmake -D USER_TLU_BUILD=ON <paht-to-cmake>`.
> 
> Let us know if it worked out this way :)
> 
> Cheers, Lennart

Yeah，I don‘t run `make install -j8` after the cmake.Thanks.

**Comment by chenzhl2018** [comment]
> No, as said this is not a missing module issue, but to me it looks like the input file is corrupt.

Maybe the reason of this issue(https://github.com/eudaq/eudaq/issues/683) is what you have said.
