### ISSUE TITLE
Fail to load module binary (libeudaq_module_caribou.so)

### ISSUE THREAD

**Issue by chenzhl2018** [eudaq/eudaq#681]
Hi,
When I run corryvreckan with eudaq2,there is a little issue showed below.
I don't know if this will affect the results.How should I do to deal with it?
Thanks in advance.

`[zchen@ui01 test3]$ ./corryvreckan/bin/corry -c bttb10_tutorial_corryvreckan/03_desy/01_tlu_mimosa26_timepix3.conf 
[2022-08-27 13:43:43.825] () [unknown sender]Fail to load module binary (libeudaq_module_caribou.so)
A dynamic linking error occurred: (/cvmfs/sft.cern.ch/lcg/releases/gcc/10.3.0-f5826/x86_64-centos7/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /ustcfs2/zchen/test3/peary/lib/libPearyDeviceAD9249.so))
|13:43:43.833|  (STATUS) Welcome to Corryvreckan v2.0+845^g3f911d80
|13:43:43.836|  (STATUS) Loading detector TLU_0
|13:43:43.836| (WARNING) No material budget given for TLU_0, assuming 0
|13:43:43.836|  (STATUS) Loading detector MIMOSA26_0
|13:43:43.838|    (INFO) 670 masked pixels
|13:43:43.839|  (STATUS) Loading detector MIMOSA26_1
|13:43:43.840|    (INFO) 655 masked pixels
|13:43:43.841|  (STATUS) Loading detector MIMOSA26_2
|13:43:43.842|    (INFO) 593 masked pixels
|13:43:43.843|  (STATUS) Loading detector ATLASPix_0
|13:43:43.844|    (INFO) 8 masked pixels
|13:43:43.844|  (STATUS) Loading detector MIMOSA26_3
|13:43:43.846|    (INFO) 412 masked pixels
|13:43:43.846|  (STATUS) Loading detector MIMOSA26_4
|13:43:43.848|    (INFO) 759 masked pixels
|13:43:43.848|  (STATUS) Loading detector MIMOSA26_5
|13:43:43.850|    (INFO) 785 masked pixels
|13:43:43.851|  (STATUS) Loaded 9 detectors         
|13:43:44.709|  (STATUS) Loading module EventLoaderEUDAQ2
|13:43:44.714|    (INFO) [C:EventLoaderEUDAQ2:TLU_0] Setting EUDAQ2 log level to "ERROR"
|13:43:44.714|  (STATUS) Loading module EventLoaderEUDAQ2
|13:43:44.714|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_0] Setting EUDAQ2 log level to "ERROR"
|13:43:44.714|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_1] Setting EUDAQ2 log level to "ERROR"
|13:43:44.715|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_2] Setting EUDAQ2 log level to "ERROR"
|13:43:44.715|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_3] Setting EUDAQ2 log level to "ERROR"
|13:43:44.715|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_4] Setting EUDAQ2 log level to "ERROR"
|13:43:44.715|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_5] Setting EUDAQ2 log level to "ERROR"
|13:43:44.715|  (STATUS) Loading module EventLoaderEUDAQ2
|13:43:44.716|    (INFO) [C:EventLoaderEUDAQ2:Timepix3_0] Setting EUDAQ2 log level to "ERROR"
|13:43:44.719|  (STATUS) Loaded 17 module instances 
|13:43:44.719|  (STATUS) =================| Initializing modules |==================
|13:43:45.620|  (STATUS) [I:Tracking4D] Initializing "Tracking4D"                                     
|13:43:45.642|  (STATUS) ========================| Event loop |========================
|13:44:27.252|  (STATUS) Ev: 24.6k Px: 2.95M Tr: 49.9k (2.03/ev) t = 49.2668s 
|13:44:27.323|  (STATUS) ===================| Finalising modules |===================
|13:44:27.323|    (INFO) [F:EventLoaderEUDAQ2:TLU_0] Found 0 hits in the data.
|13:44:28.028|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_0] Found 480808 hits in the data.
|13:44:28.511|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_1] Found 431575 hits in the data.
|13:44:29.048|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_2] Found 425273 hits in the data.
|13:44:29.493|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_3] Found 437493 hits in the data.
|13:44:29.922|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_4] Found 431767 hits in the data.
|13:44:30.327|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_5] Found 435146 hits in the data.
|13:44:30.744|    (INFO) [F:EventLoaderEUDAQ2:Timepix3_0] Found 316284 hits in the data.
|13:44:33.431|  (STATUS) Wrote histogram output file to "/ustcfs2/zchen/test3/output/01_histograms_tlu_mimosa26_timepix3.root"
|13:44:33.431|  (STATUS) ===============| Wall-clock timing (seconds) |================
|13:44:33.431|  (STATUS)    EventLoaderEUDAQ2 :      TLU_0  --  4.40449s = 0.178718ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_0  --  3.43540s = 0.139395ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_1  --  3.30121s = 0.133950ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_2  --  3.34230s = 0.135618ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_3  --  3.41786s = 0.138684ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_4  --  3.51427s = 0.142596ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_5  --  3.63958s = 0.147680ms/evt
|13:44:33.432|  (STATUS)    EventLoaderEUDAQ2 : Timepix3_0  --  2.81125s = 0.114070ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_0  --  0.74587s = 0.030265ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_1  --  0.56230s = 0.022816ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_2  --  0.54699s = 0.022195ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : ATLASPix_0  --  0.02767s = 0.001123ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_3  --  0.56467s = 0.022912ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_4  --  0.55320s = 0.022447ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : MIMOSA26_5  --  0.55623s = 0.022570ms/evt
|13:44:33.432|  (STATUS)         Clustering4D : Timepix3_0  --  0.29230s = 0.011861ms/evt
|13:44:33.432|  (STATUS)           Tracking4D               --  9.54187s = 0.387173ms/evt
|13:44:33.432|  (STATUS) ==============================================================
`

**Comment by simonspa** [comment]
Looks like you compiled different libraries with different compiler and 
glibc versions. Please make sure to use the same toolkit for all libraries 
that need to work together

**Comment by chenzhl2018** [comment]
Hi，
Yeah，you are right.Thank you very much.

**Comment by chenzhl2018** [comment]
Hi，@ simonspa
I find another question：what is the meaning of this：
`(INFO) [C:EventLoaderEUDAQ2:TLU_0] Setting EUDAQ2 log level to "ERROR"`
Does it affect the final results?How should I do next?Thanks in advance.

```
[zchen@ui01 test3]$ ./corryvreckan/bin/corry -c bttb10_tutorial_corryvreckan/03_desy/01_tlu_mimosa26_timepix3.conf 
|15:24:04.699|  (STATUS) Welcome to Corryvreckan v2.0+845^g3f911d80
|15:24:04.700|  (STATUS) Loading detector TLU_0
|15:24:04.700| (WARNING) No material budget given for TLU_0, assuming 0
|15:24:04.700|  (STATUS) Loading detector MIMOSA26_0
|15:24:04.704|    (INFO) 670 masked pixels
|15:24:04.705|  (STATUS) Loading detector MIMOSA26_1
|15:24:04.708|    (INFO) 655 masked pixels
|15:24:04.709|  (STATUS) Loading detector MIMOSA26_2
|15:24:04.713|    (INFO) 593 masked pixels
|15:24:04.713|  (STATUS) Loading detector ATLASPix_0
|15:24:04.716|    (INFO) 8 masked pixels
|15:24:04.717|  (STATUS) Loading detector MIMOSA26_3
|15:24:04.720|    (INFO) 412 masked pixels
|15:24:04.721|  (STATUS) Loading detector MIMOSA26_4
|15:24:04.725|    (INFO) 759 masked pixels
|15:24:04.725|  (STATUS) Loading detector MIMOSA26_5
|15:24:04.729|    (INFO) 785 masked pixels
|15:24:04.730|  (STATUS) Loaded 9 detectors         
|15:24:04.731| (WARNING) Main ROOT file /ustcfs2/zchen/test3/output/01_histograms_tlu_mimosa26_timepix3.root exists and will be overwritten.
|15:24:05.805|  (STATUS) Loading module EventLoaderEUDAQ2
|15:24:05.814|    (INFO) [C:EventLoaderEUDAQ2:TLU_0] Setting EUDAQ2 log level to "ERROR"
|15:24:05.815|  (STATUS) Loading module EventLoaderEUDAQ2
|15:24:05.815|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_0] Setting EUDAQ2 log level to "ERROR"
|15:24:05.815|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_1] Setting EUDAQ2 log level to "ERROR"
|15:24:05.815|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_2] Setting EUDAQ2 log level to "ERROR"
|15:24:05.816|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_3] Setting EUDAQ2 log level to "ERROR"
|15:24:05.816|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_4] Setting EUDAQ2 log level to "ERROR"
|15:24:05.816|    (INFO) [C:EventLoaderEUDAQ2:MIMOSA26_5] Setting EUDAQ2 log level to "ERROR"
|15:24:05.816|  (STATUS) Loading module EventLoaderEUDAQ2
|15:24:05.818|    (INFO) [C:EventLoaderEUDAQ2:Timepix3_0] Setting EUDAQ2 log level to "ERROR"
|15:24:05.823|  (STATUS) Loaded 17 module instances 
|15:24:05.823|  (STATUS) =================| Initializing modules |==================
|15:24:06.760|  (STATUS) [I:Tracking4D] Initializing "Tracking4D"                                     
|15:24:06.785|  (STATUS) ========================| Event loop |========================
|15:24:48.945|  (STATUS) Ev: 24.6k Px: 2.95M Tr: 49.9k (2.03/ev) t = 49.2668s 
|15:24:49.018|  (STATUS) ===================| Finalising modules |===================
|15:24:49.018|    (INFO) [F:EventLoaderEUDAQ2:TLU_0] Found 0 hits in the data.
|15:24:49.728|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_0] Found 480808 hits in the data.
|15:24:50.222|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_1] Found 431575 hits in the data.
|15:24:50.700|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_2] Found 425273 hits in the data.
|15:24:51.203|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_3] Found 437493 hits in the data.
|15:24:51.685|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_4] Found 431767 hits in the data.
|15:24:52.149|    (INFO) [F:EventLoaderEUDAQ2:MIMOSA26_5] Found 435146 hits in the data.
|15:24:52.618|    (INFO) [F:EventLoaderEUDAQ2:Timepix3_0] Found 316284 hits in the data.
|15:24:55.200|  (STATUS) Wrote histogram output file to "/ustcfs2/zchen/test3/output/01_histograms_tlu_mimosa26_timepix3.root"
|15:24:55.201|  (STATUS) ===============| Wall-clock timing (seconds) |================
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 :      TLU_0  --  4.79727s = 0.194655ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_0  --  3.51764s = 0.142733ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_1  --  3.30724s = 0.134195ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_2  --  3.36994s = 0.136739ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_3  --  3.43119s = 0.139225ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_4  --  3.53580s = 0.143469ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : MIMOSA26_5  --  3.66531s = 0.148724ms/evt
|15:24:55.201|  (STATUS)    EventLoaderEUDAQ2 : Timepix3_0  --  2.91683s = 0.118354ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_0  --  0.75629s = 0.030687ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_1  --  0.56695s = 0.023005ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_2  --  0.55141s = 0.022374ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : ATLASPix_0  --  0.02446s = 0.000993ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_3  --  0.56732s = 0.023020ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_4  --  0.55703s = 0.022602ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : MIMOSA26_5  --  0.56179s = 0.022795ms/evt
|15:24:55.201|  (STATUS)         Clustering4D : Timepix3_0  --  0.29833s = 0.012105ms/evt
|15:24:55.201|  (STATUS)           Tracking4D               --  9.37711s = 0.380487ms/evt
|15:24:55.201|  (STATUS) ==============================================================

```

**Comment by simonspa** [comment]
Well what shall I say 🤷  it sets the eudaq logging level to report all ERROR messages

**Comment by chenzhl2018** [comment]
Does it mean there is an error in the configuration files? I am new to this field. I have to learn more details. Please forgive me if I ask stupid questions.

**Comment by arummler** [comment]
No. The message is perfectly normal and just informs you that only real "errors" will be reported. The integrated logging system allows to assign each message a severity level. Below the selected level they are not reported.  Lower levels would be e.g. INFO, DEBUG, etc. which would potentially generate thousands of output lines.

**Comment by chenzhl2018** [comment]
Ok, I have got it. Thanks for your patient answers.
