### ISSUE TITLE
TluRawEvent2StdEventConverter.cc fine timing difference bug

### ISSUE THREAD

**Issue by c2bdii** [eudaq/eudaq#686]
In TluRawEvent2StdEventConverter.cc, near the end, it calculates differences between all TDCs. ...from differences 23 onwards, it has the wrong first value: 

`
d2->SetTag("DIFF_FINETS23_del_ns", std::to_string((finets3_ns -
finets3_ns)).c_str());

should be: 
d2->SetTag("DIFF_FINETS23_del_ns", std::to_string((finets***2***_ns -
finets3_ns)).c_str()); 
`

and so on?

**Comment by simonspa** [comment]
That is a correct assessment, thanks. Likely a copy&paste bug.
Would you be so kind and submit a fix as pull request?

**Comment by simonspa** [comment]
Closed via #688
