### ISSUE TITLE
MVD producer fails to build

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#74]
On Linux with GCC 4.7 the MVD producer does not compile:
```
/home/hperrey/src/eudaq/producers/mvd/include/ModV550.hh:10:27: fatal error: VMEInterface.hh: No such file or directory
```

On Windows 7 with MSVC12 errors due to inclusion of ```unistd.h``` occur.

**Comment by arummler** [comment]
Producer MVD has been removed completely as obsolete with #300.
