### ISSUE TITLE
Parts of the (LaTeX) manual are outdated

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#77]
The manual still has _many_ references to the data reduction boards (EUDRB), VME and their libraries/producers required for operating the original implementation of the JRA1 EUDET telescope; this should be updated to reflect the current generation of EUDET/AIDA telescopes based on the FlexRIO/NI-crate readout.

Even though the information on the EUDRBs is technically still correct, it might cause confusion for new users and should at least be removed.

**Comment by arummler** [comment]
Documentation both for eudaq1 and eudaq2 has been completely reworked. There is always space for improvement but at least the old stuff should be gone by now.
