### ISSUE TITLE
Request for more detailed instructions in installing C++11 complier on Scientific Linux

### ISSUE THREAD

**Issue by DavidCussans** [eudaq/eudaq#78]
Hi,

I am trying to build EUDAQ ( wanting on the new miniTLU code ) on a SLC 6.5 box. ( I want Scientific Linux since it makes is easy to install IPBus ).

I am running into trouble with getting a C++11 compatible compiler.

I followed the instructions in section 2.3 of http://eudaq.github.io/manual/EUDAQUserManual.pdf and installed the "Developer Toolset" http://linux.web.cern.ch/linux/devtoolset/ ( I installed devtoolset-2 ).

I then entered a bash shell with GCC 4.8 in the path:

```
scl enable devtoolset-2 bash

gcc --version then indicates 4.8
```

but when I "cd eudaq/build" and "cmake .." I am get "CMake Error at cmake/Platform.cmake:10 .... Please use a fully C++11 compatible compiler"

... any suggestions? I'm sure I am just using the wrong version of something, but I can't find instructions anywhere....

**Comment by simonspa** [comment]
The problem most likely was leftover caches from a previous call to CMake. Always make sure to `rm -rf` the build directory after changing system libraries or compiler.
