### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by rubinsky** [eudaq/eudaq#81]
Ubuntu 14.04
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
make install failes with the following:

/home/ilcsoft/v01-17-05-trunk/v01-17-05/Eutelescope/trunk/external/eudaq/trunk/monitors/offlinemon/src/Planes.cpp:175:47: error: no matching function for call to ‘find(std::vector<hit>::iterator, std::vector<hit>::iterator, hit&)’
   if (find( dummy.begin(), dummy.end(),current)== dummy.end()){
                                               ^

**Comment by simonspa** [comment]
Fixed with 2e4c1aa.
