### ISSUE TITLE
Bug: manual doesn't compile under windows 

### ISSUE THREAD

**Issue by RPeschke** [eudaq/eudaq#89]
it fails with the following error massage:

Error	102	error MSB6006: "cmd.exe" exited with code 4.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	dvi

**Comment by simonspa** [comment]
@RPeschke is this still a problem? If not, please close...

**Comment by arummler** [comment]
Needs to be rechecked. I can also ad it to CI, similar as linux if necessary.

**Comment by arummler** [comment]
Tested it on windows 7 / Miktex and no problem observed. Closing this issue, please open a new one if it reoccures.
