### ISSUE TITLE
Future of EUTelPixelDetector

### ISSUE THREAD

**Issue by tbisanz** [eudaq/eudaq#90]
As far as I unserstand the EUTelPixelDetector and derived classes store some general information for EUTelescope - e.g. read-out mode (zs/non-zs) or max/min pixel indices.
This code was recently moved from EUTelescope to EUDAQ, but it is not really maintained nor used actively. Are there any future plans for it?
As we don't plan on using it in EUTelescope I guess (we have all this info also in GEAR) it should either be removed or at least documented.

Cheers,
Tobias

**Comment by simonspa** [comment]
Is it used anywhere currently? Otherwise in voting for removal, unmaintained unused code has to go.

**Comment by Eyiliu** [comment]
It looks like that the  EUTelPixelDetector  class have been removed.
